# canonical data version: 2.0.0
# This file was generated by a script.

using Test

include("allergies.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# Given a number and a substance, indicate whether Tom is allergic 
# to that substance.

@testset "testing for eggs allergy" begin
    @testset "not allergic to anything" begin
        @test allergic_to("eggs", 0) == false
    end
    @testset "allergic only to eggs" begin
        @test allergic_to("eggs", 1) == true
    end
    @testset "allergic to eggs and something else" begin
        @test allergic_to("eggs", 3) == true
    end
    @testset "allergic to something, but not eggs" begin
        @test allergic_to("eggs", 2) == false
    end
    @testset "allergic to everything" begin
        @test allergic_to("eggs", 255) == true
    end
end

@testset "testing for peanuts allergy" begin
    @testset "not allergic to anything" begin
        @test allergic_to("peanuts", 0) == false
    end
    @testset "allergic only to peanuts" begin
        @test allergic_to("peanuts", 2) == true
    end
    @testset "allergic to peanuts and something else" begin
        @test allergic_to("peanuts", 7) == true
    end
    @testset "allergic to something, but not peanuts" begin
        @test allergic_to("peanuts", 5) == false
    end
    @testset "allergic to everything" begin
        @test allergic_to("peanuts", 255) == true
    end
end

@testset "testing for shellfish allergy" begin
    @testset "not allergic to anything" begin
        @test allergic_to("shellfish", 0) == false
    end
    @testset "allergic only to shellfish" begin
        @test allergic_to("shellfish", 4) == true
    end
    @testset "allergic to shellfish and something else" begin
        @test allergic_to("shellfish", 14) == true
    end
    @testset "allergic to something, but not shellfish" begin
        @test allergic_to("shellfish", 10) == false
    end
    @testset "allergic to everything" begin
        @test allergic_to("shellfish", 255) == true
    end
end

@testset "testing for strawberries allergy" begin
    @testset "not allergic to anything" begin
        @test allergic_to("strawberries", 0) == false
    end
    @testset "allergic only to strawberries" begin
        @test allergic_to("strawberries", 8) == true
    end
    @testset "allergic to strawberries and something else" begin
        @test allergic_to("strawberries", 28) == true
    end
    @testset "allergic to something, but not strawberries" begin
        @test allergic_to("strawberries", 20) == false
    end
    @testset "allergic to everything" begin
        @test allergic_to("strawberries", 255) == true
    end
end

@testset "testing for tomatoes allergy" begin
    @testset "not allergic to anything" begin
        @test allergic_to("tomatoes", 0) == false
    end
    @testset "allergic only to tomatoes" begin
        @test allergic_to("tomatoes", 16) == true
    end
    @testset "allergic to tomatoes and something else" begin
        @test allergic_to("tomatoes", 56) == true
    end
    @testset "allergic to something, but not tomatoes" begin
        @test allergic_to("tomatoes", 40) == false
    end
    @testset "allergic to everything" begin
        @test allergic_to("tomatoes", 255) == true
    end
end

@testset "testing for chocolate allergy" begin
    @testset "not allergic to anything" begin
        @test allergic_to("chocolate", 0) == false
    end
    @testset "allergic only to chocolate" begin
        @test allergic_to("chocolate", 32) == true
    end
    @testset "allergic to chocolate and something else" begin
        @test allergic_to("chocolate", 112) == true
    end
    @testset "allergic to something, but not chocolate" begin
        @test allergic_to("chocolate", 80) == false
    end
    @testset "allergic to everything" begin
        @test allergic_to("chocolate", 255) == true
    end
end

@testset "testing for pollen allergy" begin
    @testset "not allergic to anything" begin
        @test allergic_to("pollen", 0) == false
    end
    @testset "allergic only to pollen" begin
        @test allergic_to("pollen", 64) == true
    end
    @testset "allergic to pollen and something else" begin
        @test allergic_to("pollen", 224) == true
    end
    @testset "allergic to something, but not pollen" begin
        @test allergic_to("pollen", 160) == false
    end
    @testset "allergic to everything" begin
        @test allergic_to("pollen", 255) == true
    end
end

@testset "testing for cats allergy" begin
    @testset "not allergic to anything" begin
        @test allergic_to("cats", 0) == false
    end
    @testset "allergic only to cats" begin
        @test allergic_to("cats", 128) == true
    end
    @testset "allergic to cats and something else" begin
        @test allergic_to("cats", 192) == true
    end
    @testset "allergic to something, but not cats" begin
        @test allergic_to("cats", 64) == false
    end
    @testset "allergic to everything" begin
        @test allergic_to("cats", 255) == true
    end
end

@testset "list when:" begin
    @testset "no allergies" begin
        @test list(0) == []
    end
    @testset "just eggs" begin
        @test list(1) == ["eggs"]
    end
    @testset "just peanuts" begin
        @test list(2) == ["peanuts"]
    end
    @testset "just strawberries" begin
        @test list(8) == ["strawberries"]
    end
    @testset "eggs and peanuts" begin
        @test list(3) == ["eggs", "peanuts"]
    end
    @testset "more than eggs but not peanuts" begin
        @test list(5) == ["eggs", "shellfish"]
    end
    @testset "lots of stuff" begin
        @test list(248) == ["strawberries", "tomatoes", "chocolate", "pollen", "cats"]
    end
    @testset "everything" begin
        @test list(255) == ["eggs", "peanuts", "shellfish", "strawberries", "tomatoes", "chocolate", "pollen", "cats"]
    end
    @testset "no allergen score parts" begin
        @test list(509) == ["eggs", "shellfish", "strawberries", "tomatoes", "chocolate", "pollen", "cats"]
    end
end

