# canonical data version: 1.2.0
# This file was generated by a script.

using Test

include("atbash-cipher.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# The tests are divided into two groups: 
# * Encoding from English to atbash cipher
# * Decoding from atbash cipher to all-lowercase-mashed-together English

@testset "encode" begin
    @testset "encode yes" begin
        @test encode("yes") == "bvh"
    end
    @testset "encode no" begin
        @test encode("no") == "ml"
    end
    @testset "encode OMG" begin
        @test encode("OMG") == "lnt"
    end
    @testset "encode spaces" begin
        @test encode("O M G") == "lnt"
    end
    @testset "encode mindblowingly" begin
        @test encode("mindblowingly") == "nrmwy oldrm tob"
    end
    @testset "encode numbers" begin
        @test encode("Testing,1 2 3, testing.") == "gvhgr mt123 gvhgr mt"
    end
    @testset "encode deep thought" begin
        @test encode("Truth is fiction.") == "gifgs rhurx grlm"
    end
    @testset "encode all the letters" begin
        @test encode("The quick brown fox jumps over the lazy dog.") == "gsvjf rxpyi ldmul cqfnk hlevi gsvoz abwlt"
    end
end

@testset "decode" begin
    @testset "decode exercism" begin
        @test decode("vcvix rhn") == "exercism"
    end
    @testset "decode a sentence" begin
        @test decode("zmlyh gzxov rhlug vmzhg vkkrm thglm v") == "anobstacleisoftenasteppingstone"
    end
    @testset "decode numbers" begin
        @test decode("gvhgr mt123 gvhgr mt") == "testing123testing"
    end
    @testset "decode all the letters" begin
        @test decode("gsvjf rxpyi ldmul cqfnk hlevi gsvoz abwlt") == "thequickbrownfoxjumpsoverthelazydog"
    end
    @testset "decode with too many spaces" begin
        @test decode("vc vix    r hn") == "exercism"
    end
    @testset "decode with no spaces" begin
        @test decode("zmlyhgzxovrhlugvmzhgvkkrmthglmv") == "anobstacleisoftenasteppingstone"
    end
end

