# canonical data version: 1.1.0
# This file was generated by a script.

using Test

include("binary.jl")

@testset "binary 0 is decimal 0" begin
    @test decimal("0") == 0
end

@testset "binary 1 is decimal 1" begin
    @test decimal("1") == 1
end

@testset "binary 10 is decimal 2" begin
    @test decimal("10") == 2
end

@testset "binary 11 is decimal 3" begin
    @test decimal("11") == 3
end

@testset "binary 100 is decimal 4" begin
    @test decimal("100") == 4
end

@testset "binary 1001 is decimal 9" begin
    @test decimal("1001") == 9
end

@testset "binary 11010 is decimal 26" begin
    @test decimal("11010") == 26
end

@testset "binary 10001101000 is decimal 1128" begin
    @test decimal("10001101000") == 1128
end

@testset "binary ignores leading zeros" begin
    @test decimal("000011111") == 31
end

@testset "2 is not a valid binary digit" begin
    @test decimal("2") == nothing
end

@testset "a number containing a non-binary digit is invalid" begin
    @test decimal("01201") == nothing
end

@testset "a number with trailing non-binary characters is invalid" begin
    @test decimal("10nope") == nothing
end

@testset "a number with leading non-binary characters is invalid" begin
    @test decimal("nope10") == nothing
end

@testset "a number with internal non-binary characters is invalid" begin
    @test decimal("10nope10") == nothing
end

@testset "a number and a word whitespace separated is invalid" begin
    @test decimal("001 nope") == nothing
end

