# canonical data version: 1.4.0
# This file was generated by a script.

using Test

include("book-store.jl")

@testset "Return the total basket price after applying the best discount." begin
    @testset "Only a single book" begin
        @test total([1]) == 800
    end
    @testset "Two of the same book" begin
        @test total([2, 2]) == 1600
    end
    @testset "Empty basket" begin
        @test total([]) == 0
    end
    @testset "Two different books" begin
        @test total([1, 2]) == 1520
    end
    @testset "Three different books" begin
        @test total([1, 2, 3]) == 2160
    end
    @testset "Four different books" begin
        @test total([1, 2, 3, 4]) == 2560
    end
    @testset "Five different books" begin
        @test total([1, 2, 3, 4, 5]) == 3000
    end
    @testset "Two groups of four is cheaper than group of five plus group of three" begin
        @test total([1, 1, 2, 2, 3, 3, 4, 5]) == 5120
    end
    @testset "Two groups of four is cheaper than groups of five and three" begin
        @test total([1, 1, 2, 3, 4, 4, 5, 5]) == 5120
    end
    @testset "Group of four plus group of two is cheaper than two groups of three" begin
        @test total([1, 1, 2, 2, 3, 4]) == 4080
    end
    @testset "Two each of first 4 books and 1 copy each of rest" begin
        @test total([1, 1, 2, 2, 3, 3, 4, 4, 5]) == 5560
    end
    @testset "Two copies of each book" begin
        @test total([1, 1, 2, 2, 3, 3, 4, 4, 5, 5]) == 6000
    end
    @testset "Three copies of first book and 2 each of remaining" begin
        @test total([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 1]) == 6800
    end
    @testset "Three each of first 2 books and 2 each of remaining books" begin
        @test total([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 1, 2]) == 7520
    end
    @testset "Four groups of four are cheaper than two groups each of five and three" begin
        @test total([1, 1, 2, 2, 3, 3, 4, 5, 1, 1, 2, 2, 3, 3, 4, 5]) == 10240
    end
end

