# canonical data version: 1.3.0
# This file was generated by a script.

using Test

include("change.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# Given an infinite supply of coins with different values, 
# find the smallest number of coins needed to make a desired 
# amount of change.

@testset "single coin change" begin
    @test find_fewest_coins([1, 5, 10, 25, 100], 25) == [25]
end

@testset "multiple coin change" begin
    @test find_fewest_coins([1, 5, 10, 25, 100], 15) == [5, 10]
end

@testset "change with Lilliputian Coins" begin
    @test find_fewest_coins([1, 4, 15, 20, 50], 23) == [4, 4, 15]
end

@testset "change with Lower Elbonia Coins" begin
    @test find_fewest_coins([1, 5, 10, 21, 25], 63) == [21, 21, 21]
end

@testset "large target values" begin
    @test find_fewest_coins([1, 2, 5, 10, 20, 50, 100], 999) == [2, 2, 5, 20, 20, 50, 100, 100, 100, 100, 100, 100, 100, 100, 100]
end

@testset "possible change without unit coins available" begin
    @test find_fewest_coins([2, 5, 10, 20, 50], 21) == [2, 2, 2, 5, 10]
end

@testset "another possible change without unit coins available" begin
    @test find_fewest_coins([4, 5], 27) == [4, 4, 4, 5, 5, 5]
end

@testset "no coins make 0 change" begin
    @test find_fewest_coins([1, 5, 10, 21, 25], 0) == []
end

@testset "error testing for change smaller than the smallest of coins" begin
    @test_throws ArgumentError find_fewest_coins([5, 10], 3)
end

@testset "error if no combination can add up to target" begin
    @test_throws ArgumentError find_fewest_coins([5, 10], 94)
end

@testset "cannot find negative change values" begin
    @test_throws ArgumentError find_fewest_coins([1, 2, 5], -5)
end

