# canonical data version: 1.1.0
# This file was generated by a script.

using Test

include("connect.jl")

@testset "an empty board has no winner" begin
    @test winner([". . . . .", " . . . . .", "  . . . . .", "   . . . . .", "    . . . . ."]) == ""
end

@testset "X can win on a 1x1 board" begin
    @test winner(["X"]) == "X"
end

@testset "O can win on a 1x1 board" begin
    @test winner(["O"]) == "O"
end

@testset "only edges does not make a winner" begin
    @test winner(["O O O X", " X . . X", "  X . . X", "   X O O O"]) == ""
end

@testset "illegal diagonal does not make a winner" begin
    @test winner(["X O . .", " O X X X", "  O X O .", "   . O X .", "    X X O O"]) == ""
end

@testset "nobody wins crossing adjacent angles" begin
    @test winner(["X . . .", " . X O .", "  O . X O", "   . O . X", "    . . O ."]) == ""
end

@testset "X wins crossing from left to right" begin
    @test winner([". O . .", " O X X X", "  O X O .", "   X X O X", "    . O X ."]) == "X"
end

@testset "O wins crossing from top to bottom" begin
    @test winner([". O . .", " O X X X", "  O O O .", "   X X O X", "    . O X ."]) == "O"
end

@testset "X wins using a convoluted path" begin
    @test winner([". X X . .", " X . X . X", "  . X . X .", "   . X X . .", "    O O O O O"]) == "X"
end

@testset "X wins using a spiral path" begin
    @test winner(["O X X X X X X X X", " O X O O O O O O O", "  O X O X X X X X O", "   O X O X O O O X O", "    O X O X X X O X O", "     O X O O O X O X O", "      O X X X X X O X O", "       O O O O O O O X O", "        X X X X X X X X O"]) == "X"
end

