# canonical data version: 1.1.0
# This file was generated by a script.

using Test

include("dnd-character.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# The random generator 'ability' can be property-tested.
# The pure function 'modifier' can be tested totally.
# The random generator 'character' should return some
# kind of structure with six random abilities and a
# hitpoint score. This structure can be property-tested
# in the same way as 'ability' and 'modifier'.
# 
# It may be fun to provide a 'name' property for characters
# that may or may not be randomly generated but not tested.
# 
# Many programming languages feature property-based test
# frameworks. For a language-agnostic introduction to
# property-based testing, see:
# 
# https://hypothesis.works/articles/what-is-property-based-testing/

@testset "ability modifier" begin
    @testset "ability modifier for score 3 is -4" begin
        @test modifier(3) == -4
    end
    @testset "ability modifier for score 4 is -3" begin
        @test modifier(4) == -3
    end
    @testset "ability modifier for score 5 is -3" begin
        @test modifier(5) == -3
    end
    @testset "ability modifier for score 6 is -2" begin
        @test modifier(6) == -2
    end
    @testset "ability modifier for score 7 is -2" begin
        @test modifier(7) == -2
    end
    @testset "ability modifier for score 8 is -1" begin
        @test modifier(8) == -1
    end
    @testset "ability modifier for score 9 is -1" begin
        @test modifier(9) == -1
    end
    @testset "ability modifier for score 10 is 0" begin
        @test modifier(10) == 0
    end
    @testset "ability modifier for score 11 is 0" begin
        @test modifier(11) == 0
    end
    @testset "ability modifier for score 12 is +1" begin
        @test modifier(12) == 1
    end
    @testset "ability modifier for score 13 is +1" begin
        @test modifier(13) == 1
    end
    @testset "ability modifier for score 14 is +2" begin
        @test modifier(14) == 2
    end
    @testset "ability modifier for score 15 is +2" begin
        @test modifier(15) == 2
    end
    @testset "ability modifier for score 16 is +3" begin
        @test modifier(16) == 3
    end
    @testset "ability modifier for score 17 is +3" begin
        @test modifier(17) == 3
    end
    @testset "ability modifier for score 18 is +4" begin
        @test modifier(18) == 4
    end
end

@testset "random ability is within range" begin
    @test ability() == "score >= 3 && score <= 18"
end

@testset "random character is valid" begin
    @test character() == Dict("strength" => "strength >= 3 && strength <= 18", "dexterity" => "dexterity >= 3 && dexterity <= 18", "constitution" => "constitution >= 3 && constitution <= 18", "intelligence" => "intelligence >= 3 && intelligence <= 18", "wisdom" => "wisdom >= 3 && wisdom <= 18", "charisma" => "charisma >= 3 && charisma <= 18", "hitpoints" => "hitpoints == 10 + modifier(constitution)")
end

@testset "each ability is only calculated once" begin
    @test strength() == "strength == strength"
end

