# canonical data version: 1.2.0
# This file was generated by a script.

using Test

include("flatten-array.jl")

@testset "no nesting" begin
    @test flatten([0, 1, 2]) == [0, 1, 2]
end

@testset "flattens array with just integers present" begin
    @test flatten(Any[1, [2, 3, 4, 5, 6, 7], 8]) == [1, 2, 3, 4, 5, 6, 7, 8]
end

@testset "5 level nesting" begin
    @test flatten(Any[0, 2, Any[[2, 3], 8, 100, 4, [[[50]]]], -2]) == [0, 2, 2, 3, 8, 100, 4, 50, -2]
end

@testset "6 level nesting" begin
    @test flatten(Any[1, Any[2, [[3]], Any[4, [[5]]], 6, 7], 8]) == [1, 2, 3, 4, 5, 6, 7, 8]
end

@testset "6 level nest list with null values" begin
    @test flatten(Any[0, 2, Any[[2, 3], 8, [[100]], nothing, [[nothing]]], -2]) == [0, 2, 2, 3, 8, 100, -2]
end

@testset "all values in nested list are null" begin
    @test flatten(Any[nothing, [[[nothing]]], nothing, nothing, Union{Nothing, Array{Nothing,1}}[[nothing, nothing], nothing], nothing]) == []
end

