# canonical data version: 1.2.0
# This file was generated by a script.

using Test

include("grep.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
#  JSON doesn't allow for multi-line strings, so all   
#  outputs are presented here as arrays of strings.    
#  It's up to the test generator to join the lines     
#  together with line breaks.                          
#                                                      
#  The tests are divided into two groups:              
#   - Grepping a single file                           
#   - Grepping multiple files at once                  
#                                                      
#  The language track implementing this exercise       
#  should ensure that when the tests run, three files  
#  are created with the following contents. The file   
#  names and their contents are listed below:          
#                                                      
#  iliad.txt                                           
#    ---------------------------------------------     
#    |Achilles sing, O Goddess! Peleus' son;     |     
#    |His wrath pernicious, who ten thousand woes|     
#    |Caused to Achaia's host, sent many a soul  |     
#    |Illustrious into Ades premature,           |     
#    |And Heroes gave (so stood the will of Jove)|     
#    |To dogs and to all ravening fowls a prey,  |     
#    |When fierce dispute had separated once     |     
#    |The noble Chief Achilles from the son      |     
#    |Of Atreus, Agamemnon, King of men.         |     
#    ---------------------------------------------     
#                                                      
#  midsummer-night.txt                                 
#    -----------------------------------------------   
#    |I do entreat your grace to pardon me.        |   
#    |I know not by what power I am made bold,     |   
#    |Nor how it may concern my modesty,           |   
#    |In such a presence here to plead my thoughts;|   
#    |But I beseech your grace that I may know     |   
#    |The worst that may befall me in this case,   |   
#    |If I refuse to wed Demetrius.                |   
#    -----------------------------------------------   
#                                                      
#  paradise-lost.txt                                   
#    ------------------------------------------------- 
#    |Of Mans First Disobedience, and the Fruit      | 
#    |Of that Forbidden Tree, whose mortal tast      | 
#    |Brought Death into the World, and all our woe, | 
#    |With loss of Eden, till one greater Man        | 
#    |Restore us, and regain the blissful Seat,      | 
#    |Sing Heav'nly Muse, that on the secret top     | 
#    |Of Oreb, or of Sinai, didst inspire            | 
#    |That Shepherd, who first taught the chosen Seed| 
#    ------------------------------------------------- 

@testset "Test grepping a single file" begin
    @testset "One file, one match, no flags" begin
        @test grep("Agamemnon", [], ["iliad.txt"]) == ["Of Atreus, Agamemnon, King of men."]
    end
    @testset "One file, one match, print line numbers flag" begin
        @test grep("Forbidden", ["-n"], ["paradise-lost.txt"]) == ["2:Of that Forbidden Tree, whose mortal tast"]
    end
    @testset "One file, one match, case-insensitive flag" begin
        @test grep("FORBIDDEN", ["-i"], ["paradise-lost.txt"]) == ["Of that Forbidden Tree, whose mortal tast"]
    end
    @testset "One file, one match, print file names flag" begin
        @test grep("Forbidden", ["-l"], ["paradise-lost.txt"]) == ["paradise-lost.txt"]
    end
    @testset "One file, one match, match entire lines flag" begin
        @test grep("With loss of Eden, till one greater Man", ["-x"], ["paradise-lost.txt"]) == ["With loss of Eden, till one greater Man"]
    end
    @testset "One file, one match, multiple flags" begin
        @test grep("OF ATREUS, Agamemnon, KIng of MEN.", ["-n", "-i", "-x"], ["iliad.txt"]) == ["9:Of Atreus, Agamemnon, King of men."]
    end
    @testset "One file, several matches, no flags" begin
        @test grep("may", [], ["midsummer-night.txt"]) == ["Nor how it may concern my modesty,", "But I beseech your grace that I may know", "The worst that may befall me in this case,"]
    end
    @testset "One file, several matches, print line numbers flag" begin
        @test grep("may", ["-n"], ["midsummer-night.txt"]) == ["3:Nor how it may concern my modesty,", "5:But I beseech your grace that I may know", "6:The worst that may befall me in this case,"]
    end
    @testset "One file, several matches, match entire lines flag" begin
        @test grep("may", ["-x"], ["midsummer-night.txt"]) == []
    end
    @testset "One file, several matches, case-insensitive flag" begin
        @test grep("ACHILLES", ["-i"], ["iliad.txt"]) == ["Achilles sing, O Goddess! Peleus' son;", "The noble Chief Achilles from the son"]
    end
    @testset "One file, several matches, inverted flag" begin
        @test grep("Of", ["-v"], ["paradise-lost.txt"]) == ["Brought Death into the World, and all our woe,", "With loss of Eden, till one greater Man", "Restore us, and regain the blissful Seat,", "Sing Heav'nly Muse, that on the secret top", "That Shepherd, who first taught the chosen Seed"]
    end
    @testset "One file, no matches, various flags" begin
        @test grep("Gandalf", ["-n", "-l", "-x", "-i"], ["iliad.txt"]) == []
    end
    @testset "One file, one match, file flag takes precedence over line flag" begin
        @test grep("ten", ["-n", "-l"], ["iliad.txt"]) == ["iliad.txt"]
    end
    @testset "One file, several matches, inverted and match entire lines flags" begin
        @test grep("Illustrious into Ades premature,", ["-x", "-v"], ["iliad.txt"]) == ["Achilles sing, O Goddess! Peleus' son;", "His wrath pernicious, who ten thousand woes", "Caused to Achaia's host, sent many a soul", "And Heroes gave (so stood the will of Jove)", "To dogs and to all ravening fowls a prey,", "When fierce dispute had separated once", "The noble Chief Achilles from the son", "Of Atreus, Agamemnon, King of men."]
    end
end

@testset "Test grepping multiples files at once" begin
    @testset "Multiple files, one match, no flags" begin
        @test grep("Agamemnon", [], ["iliad.txt", "midsummer-night.txt", "paradise-lost.txt"]) == ["iliad.txt:Of Atreus, Agamemnon, King of men."]
    end
    @testset "Multiple files, several matches, no flags" begin
        @test grep("may", [], ["iliad.txt", "midsummer-night.txt", "paradise-lost.txt"]) == ["midsummer-night.txt:Nor how it may concern my modesty,", "midsummer-night.txt:But I beseech your grace that I may know", "midsummer-night.txt:The worst that may befall me in this case,"]
    end
    @testset "Multiple files, several matches, print line numbers flag" begin
        @test grep("that", ["-n"], ["iliad.txt", "midsummer-night.txt", "paradise-lost.txt"]) == ["midsummer-night.txt:5:But I beseech your grace that I may know", "midsummer-night.txt:6:The worst that may befall me in this case,", "paradise-lost.txt:2:Of that Forbidden Tree, whose mortal tast", "paradise-lost.txt:6:Sing Heav'nly Muse, that on the secret top"]
    end
    @testset "Multiple files, one match, print file names flag" begin
        @test grep("who", ["-l"], ["iliad.txt", "midsummer-night.txt", "paradise-lost.txt"]) == ["iliad.txt", "paradise-lost.txt"]
    end
    @testset "Multiple files, several matches, case-insensitive flag" begin
        @test grep("TO", ["-i"], ["iliad.txt", "midsummer-night.txt", "paradise-lost.txt"]) == ["iliad.txt:Caused to Achaia's host, sent many a soul", "iliad.txt:Illustrious into Ades premature,", "iliad.txt:And Heroes gave (so stood the will of Jove)", "iliad.txt:To dogs and to all ravening fowls a prey,", "midsummer-night.txt:I do entreat your grace to pardon me.", "midsummer-night.txt:In such a presence here to plead my thoughts;", "midsummer-night.txt:If I refuse to wed Demetrius.", "paradise-lost.txt:Brought Death into the World, and all our woe,", "paradise-lost.txt:Restore us, and regain the blissful Seat,", "paradise-lost.txt:Sing Heav'nly Muse, that on the secret top"]
    end
    @testset "Multiple files, several matches, inverted flag" begin
        @test grep("a", ["-v"], ["iliad.txt", "midsummer-night.txt", "paradise-lost.txt"]) == ["iliad.txt:Achilles sing, O Goddess! Peleus' son;", "iliad.txt:The noble Chief Achilles from the son", "midsummer-night.txt:If I refuse to wed Demetrius."]
    end
    @testset "Multiple files, one match, match entire lines flag" begin
        @test grep("But I beseech your grace that I may know", ["-x"], ["iliad.txt", "midsummer-night.txt", "paradise-lost.txt"]) == ["midsummer-night.txt:But I beseech your grace that I may know"]
    end
    @testset "Multiple files, one match, multiple flags" begin
        @test grep("WITH LOSS OF EDEN, TILL ONE GREATER MAN", ["-n", "-i", "-x"], ["iliad.txt", "midsummer-night.txt", "paradise-lost.txt"]) == ["paradise-lost.txt:4:With loss of Eden, till one greater Man"]
    end
    @testset "Multiple files, no matches, various flags" begin
        @test grep("Frodo", ["-n", "-l", "-x", "-i"], ["iliad.txt", "midsummer-night.txt", "paradise-lost.txt"]) == []
    end
    @testset "Multiple files, several matches, file flag takes precedence over line number flag" begin
        @test grep("who", ["-n", "-l"], ["iliad.txt", "midsummer-night.txt", "paradise-lost.txt"]) == ["iliad.txt", "paradise-lost.txt"]
    end
    @testset "Multiple files, several matches, inverted and match entire lines flags" begin
        @test grep("Illustrious into Ades premature,", ["-x", "-v"], ["iliad.txt", "midsummer-night.txt", "paradise-lost.txt"]) == ["iliad.txt:Achilles sing, O Goddess! Peleus' son;", "iliad.txt:His wrath pernicious, who ten thousand woes", "iliad.txt:Caused to Achaia's host, sent many a soul", "iliad.txt:And Heroes gave (so stood the will of Jove)", "iliad.txt:To dogs and to all ravening fowls a prey,", "iliad.txt:When fierce dispute had separated once", "iliad.txt:The noble Chief Achilles from the son", "iliad.txt:Of Atreus, Agamemnon, King of men.", "midsummer-night.txt:I do entreat your grace to pardon me.", "midsummer-night.txt:I know not by what power I am made bold,", "midsummer-night.txt:Nor how it may concern my modesty,", "midsummer-night.txt:In such a presence here to plead my thoughts;", "midsummer-night.txt:But I beseech your grace that I may know", "midsummer-night.txt:The worst that may befall me in this case,", "midsummer-night.txt:If I refuse to wed Demetrius.", "paradise-lost.txt:Of Mans First Disobedience, and the Fruit", "paradise-lost.txt:Of that Forbidden Tree, whose mortal tast", "paradise-lost.txt:Brought Death into the World, and all our woe,", "paradise-lost.txt:With loss of Eden, till one greater Man", "paradise-lost.txt:Restore us, and regain the blissful Seat,", "paradise-lost.txt:Sing Heav'nly Muse, that on the secret top", "paradise-lost.txt:Of Oreb, or of Sinai, didst inspire", "paradise-lost.txt:That Shepherd, who first taught the chosen Seed"]
    end
end

