# canonical data version: 1.7.0
# This file was generated by a script.

using Test

include("isogram.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# An isogram is a word or phrase without a repeating letter.

@testset "Check if the given string is an isogram" begin
    @testset "empty string" begin
        @test is_isogram("") == true
    end
    @testset "isogram with only lower case characters" begin
        @test is_isogram("isogram") == true
    end
    @testset "word with one duplicated character" begin
        @test is_isogram("eleven") == false
    end
    @testset "word with one duplicated character from the end of the alphabet" begin
        @test is_isogram("zzyzx") == false
    end
    @testset "longest reported english isogram" begin
        @test is_isogram("subdermatoglyphic") == true
    end
    @testset "word with duplicated character in mixed case" begin
        @test is_isogram("Alphabet") == false
    end
    @testset "word with duplicated character in mixed case, lowercase first" begin
        @test is_isogram("alphAbet") == false
    end
    @testset "hypothetical isogrammic word with hyphen" begin
        @test is_isogram("thumbscrew-japingly") == true
    end
    @testset "hypothetical word with duplicated character following hyphen" begin
        @test is_isogram("thumbscrew-jappingly") == false
    end
    @testset "isogram with duplicated hyphen" begin
        @test is_isogram("six-year-old") == true
    end
    @testset "made-up name that is an isogram" begin
        @test is_isogram("Emily Jung Schwartzkopf") == true
    end
    @testset "duplicated character in the middle" begin
        @test is_isogram("accentor") == false
    end
    @testset "same first and last characters" begin
        @test is_isogram("angola") == false
    end
end

