# canonical data version: 1.1.1
# This file was generated by a script.

using Test

include("kindergarten-garden.jl")

@testset "partial garden" begin
    @testset "garden with single student" begin
        @test plants("RC\nGG", "Alice") == ["radishes", "clover", "grass", "grass"]
    end
    @testset "different garden with single student" begin
        @test plants("VC\nRC", "Alice") == ["violets", "clover", "radishes", "clover"]
    end
    @testset "garden with two students" begin
        @test plants("VVCG\nVVRC", "Bob") == ["clover", "grass", "radishes", "clover"]
    end
    @testset "multiple students for the same garden with three students" begin
        @testset "second student's garden" begin
            @test plants("VVCCGG\nVVCCGG", "Bob") == ["clover", "clover", "clover", "clover"]
        end
        @testset "third student's garden" begin
            @test plants("VVCCGG\nVVCCGG", "Charlie") == ["grass", "grass", "grass", "grass"]
        end
    end
end

@testset "full garden" begin
    @testset "first student's garden" begin
        @test plants("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV", "Alice") == ["violets", "radishes", "violets", "radishes"]
    end
    @testset "second student's garden" begin
        @test plants("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV", "Bob") == ["clover", "grass", "clover", "clover"]
    end
    @testset "second to last student's garden" begin
        @test plants("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV", "Kincaid") == ["grass", "clover", "clover", "grass"]
    end
    @testset "last student's garden" begin
        @test plants("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV", "Larry") == ["grass", "violets", "clover", "violets"]
    end
end

