# canonical data version: 2.0.0
# This file was generated by a script.

using Test

include("matching-brackets.jl")

@testset "paired square brackets" begin
    @test is_paired("[]") == true
end

@testset "empty string" begin
    @test is_paired("") == true
end

@testset "unpaired brackets" begin
    @test is_paired("[[") == false
end

@testset "wrong ordered brackets" begin
    @test is_paired("}{") == false
end

@testset "wrong closing bracket" begin
    @test is_paired("{]") == false
end

@testset "paired with whitespace" begin
    @test is_paired("{ }") == true
end

@testset "partially paired brackets" begin
    @test is_paired("{[])") == false
end

@testset "simple nested brackets" begin
    @test is_paired("{[]}") == true
end

@testset "several paired brackets" begin
    @test is_paired("{}[]") == true
end

@testset "paired and nested brackets" begin
    @test is_paired("([{}({}[])])") == true
end

@testset "unopened closing brackets" begin
    @test is_paired("{[)][]}") == false
end

@testset "unpaired and nested brackets" begin
    @test is_paired("([{])") == false
end

@testset "paired and wrong nested brackets" begin
    @test is_paired("[({]})") == false
end

@testset "paired and incomplete brackets" begin
    @test is_paired("{}[") == false
end

@testset "too many closing brackets" begin
    @test is_paired("[]]") == false
end

@testset "math expression" begin
    @test is_paired("(((185 + 223.85) * 15) - 543)/2") == true
end

@testset "complex latex expression" begin
    @test is_paired("\\left(\\begin{array}{cc} \\frac{1}{3} & x\\\\ \\mathrm{e}^{x} &... x^2 \\end{array}\\right)") == true
end

