# canonical data version: 1.1.0
# This file was generated by a script.

using Test

include("minesweeper.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
#  The expected outputs are represented as arrays of strings to   
#  improve readability in this JSON file.                         
#  Your track may choose whether to present the input as a single 
#  string (concatenating all the lines) or as the list.           

@testset "no rows" begin
    @test annotate([]) == []
end

@testset "no columns" begin
    @test annotate([""]) == [""]
end

@testset "no mines" begin
    @test annotate(["   ", "   ", "   "]) == ["   ", "   ", "   "]
end

@testset "minefield with only mines" begin
    @test annotate(["***", "***", "***"]) == ["***", "***", "***"]
end

@testset "mine surrounded by spaces" begin
    @test annotate(["   ", " * ", "   "]) == ["111", "1*1", "111"]
end

@testset "space surrounded by mines" begin
    @test annotate(["***", "* *", "***"]) == ["***", "*8*", "***"]
end

@testset "horizontal line" begin
    @test annotate([" * * "]) == ["1*2*1"]
end

@testset "horizontal line, mines at edges" begin
    @test annotate(["*   *"]) == ["*1 1*"]
end

@testset "vertical line" begin
    @test annotate([" ", "*", " ", "*", " "]) == ["1", "*", "2", "*", "1"]
end

@testset "vertical line, mines at edges" begin
    @test annotate(["*", " ", " ", " ", "*"]) == ["*", "1", " ", "1", "*"]
end

@testset "cross" begin
    @test annotate(["  *  ", "  *  ", "*****", "  *  ", "  *  "]) == [" 2*2 ", "25*52", "*****", "25*52", " 2*2 "]
end

@testset "large minefield" begin
    @test annotate([" *  * ", "  *   ", "    * ", "   * *", " *  * ", "      "]) == ["1*22*1", "12*322", " 123*2", "112*4*", "1*22*2", "111111"]
end

