# canonical data version: 2.1.0
# This file was generated by a script.

using Test

include("nth-prime.jl")

@testset "first prime" begin
    @test prime(1) == 2
end

@testset "second prime" begin
    @test prime(2) == 3
end

@testset "sixth prime" begin
    @test prime(6) == 13
end

@testset "big prime" begin
    @test prime(10001) == 104743
end

@testset "there is no zeroth prime" begin
    @test_throws ArgumentError prime(0)
end

