# canonical data version: 1.3.0
# This file was generated by a script.

using Test

include("nucleotide-count.jl")

@testset "count all nucleotides in a strand" begin
    @testset "empty strand" begin
        @test nucleotide_counts("") == Dict("A" => 0, "C" => 0, "G" => 0, "T" => 0)
    end
    @testset "can count one nucleotide in single-character input" begin
        @test nucleotide_counts("G") == Dict("A" => 0, "C" => 0, "G" => 1, "T" => 0)
    end
    @testset "strand with repeated nucleotide" begin
        @test nucleotide_counts("GGGGGGG") == Dict("A" => 0, "C" => 0, "G" => 7, "T" => 0)
    end
    @testset "strand with multiple nucleotides" begin
        @test nucleotide_counts("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC") == Dict("A" => 20, "C" => 12, "G" => 17, "T" => 21)
    end
    @testset "strand with invalid nucleotides" begin
        @test_throws ArgumentError nucleotide_counts("AGXXACT")
    end
end

