# canonical data version: 1.2.0
# This file was generated by a script.

using Test

include("ocr-numbers.jl")

@testset "Converts lines of OCR Numbers to a string of integers" begin
    @testset "Recognizes 0" begin
        @test convert([" _ ", "| |", "|_|", "   "]) == "0"
    end
    @testset "Recognizes 1" begin
        @test convert(["   ", "  |", "  |", "   "]) == "1"
    end
    @testset "Unreadable but correctly sized inputs return ?" begin
        @test convert(["   ", "  _", "  |", "   "]) == "?"
    end
    @testset "Input with a number of lines that is not a multiple of four raises an error" begin
        @test_throws ArgumentError convert([" _ ", "| |", "   "])
    end
    @testset "Input with a number of columns that is not a multiple of three raises an error" begin
        @test_throws ArgumentError convert(["    ", "   |", "   |", "    "])
    end
    @testset "Recognizes 110101100" begin
        @test convert(["       _     _        _  _ ", "  |  || |  || |  |  || || |", "  |  ||_|  ||_|  |  ||_||_|", "                           "]) == "110101100"
    end
    @testset "Garbled numbers in a string are replaced with ?" begin
        @test convert(["       _     _           _ ", "  |  || |  || |     || || |", "  |  | _|  ||_|  |  ||_||_|", "                           "]) == "11?10?1?0"
    end
    @testset "Recognizes 2" begin
        @test convert([" _ ", " _|", "|_ ", "   "]) == "2"
    end
    @testset "Recognizes 3" begin
        @test convert([" _ ", " _|", " _|", "   "]) == "3"
    end
    @testset "Recognizes 4" begin
        @test convert(["   ", "|_|", "  |", "   "]) == "4"
    end
    @testset "Recognizes 5" begin
        @test convert([" _ ", "|_ ", " _|", "   "]) == "5"
    end
    @testset "Recognizes 6" begin
        @test convert([" _ ", "|_ ", "|_|", "   "]) == "6"
    end
    @testset "Recognizes 7" begin
        @test convert([" _ ", "  |", "  |", "   "]) == "7"
    end
    @testset "Recognizes 8" begin
        @test convert([" _ ", "|_|", "|_|", "   "]) == "8"
    end
    @testset "Recognizes 9" begin
        @test convert([" _ ", "|_|", " _|", "   "]) == "9"
    end
    @testset "Recognizes string of decimal numbers" begin
        @test convert(["    _  _     _  _  _  _  _  _ ", "  | _| _||_||_ |_   ||_||_|| |", "  ||_  _|  | _||_|  ||_| _||_|", "                              "]) == "1234567890"
    end
    @testset "Numbers separated by empty lines are recognized. Lines are joined by commas." begin
        @test convert(["    _  _ ", "  | _| _|", "  ||_  _|", "         ", "    _  _ ", "|_||_ |_ ", "  | _||_|", "         ", " _  _  _ ", "  ||_||_|", "  ||_| _|", "         "]) == "123,456,789"
    end
end

