# canonical data version: 2.0.0
# This file was generated by a script.

using Test

include("pangram.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# A pangram is a sentence using every letter of the alphabet at least once.
# Output should be a boolean denoting if the string is a pangram or not.

@testset "empty sentence" begin
    @test is_pangram("") == false
end

@testset "perfect lower case" begin
    @test is_pangram("abcdefghijklmnopqrstuvwxyz") == true
end

@testset "only lower case" begin
    @test is_pangram("the quick brown fox jumps over the lazy dog") == true
end

@testset "missing the letter 'x'" begin
    @test is_pangram("a quick movement of the enemy will jeopardize five gunboats") == false
end

@testset "missing the letter 'h'" begin
    @test is_pangram("five boxing wizards jump quickly at it") == false
end

@testset "with underscores" begin
    @test is_pangram("the_quick_brown_fox_jumps_over_the_lazy_dog") == true
end

@testset "with numbers" begin
    @test is_pangram("the 1 quick brown fox jumps over the 2 lazy dogs") == true
end

@testset "missing letters replaced by numbers" begin
    @test is_pangram("7h3 qu1ck brown fox jumps ov3r 7h3 lazy dog") == false
end

@testset "mixed case and punctuation" begin
    @test is_pangram("\"Five quacking Zephyrs jolt my wax bed.\"") == true
end

@testset "case insensitive" begin
    @test is_pangram("the quick brown fox jumps over with lazy FX") == false
end

