# canonical data version: 1.5.0
# This file was generated by a script.

using Test

include("pascals-triangle.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# Expectations are represented here as an array of arrays.
# How you represent this idiomatically in your language is up to you.

@testset "Given a count, return a collection of that many rows of pascal's triangle" begin
    @testset "zero rows" begin
        @test rows(0) == []
    end
    @testset "single row" begin
        @test rows(1) == [[1]]
    end
    @testset "two rows" begin
        @test rows(2) == [[1], [1, 1]]
    end
    @testset "three rows" begin
        @test rows(3) == [[1], [1, 1], [1, 2, 1]]
    end
    @testset "four rows" begin
        @test rows(4) == [[1], [1, 1], [1, 2, 1], [1, 3, 3, 1]]
    end
    @testset "five rows" begin
        @test rows(5) == [[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]]
    end
    @testset "six rows" begin
        @test rows(6) == [[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1], [1, 5, 10, 10, 5, 1]]
    end
    @testset "ten rows" begin
        @test rows(10) == [[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1], [1, 5, 10, 10, 5, 1], [1, 6, 15, 20, 15, 6, 1], [1, 7, 21, 35, 35, 21, 7, 1], [1, 8, 28, 56, 70, 56, 28, 8, 1], [1, 9, 36, 84, 126, 126, 84, 36, 9, 1]]
    end
end

