# canonical data version: 1.1.0
# This file was generated by a script.

using Test

include("prime-factors.jl")

@testset "returns prime factors for the given input number" begin
    @testset "no factors" begin
        @test factors(1) == []
    end
    @testset "prime number" begin
        @test factors(2) == [2]
    end
    @testset "square of a prime" begin
        @test factors(9) == [3, 3]
    end
    @testset "cube of a prime" begin
        @test factors(8) == [2, 2, 2]
    end
    @testset "product of primes and non-primes" begin
        @test factors(12) == [2, 2, 3]
    end
    @testset "product of primes" begin
        @test factors(901255) == [5, 17, 23, 461]
    end
    @testset "factors include a large prime" begin
        @test factors(93819012551) == [11, 9539, 894119]
    end
end

