# canonical data version: 1.1.0
# This file was generated by a script.

using Test

include("rail-fence-cipher.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# The tests do not expect any normalization or cleaning.
# That trade is tested in enough other exercises.

@testset "encode" begin
    @testset "encode with two rails" begin
        @test encode("XOXOXOXOXOXOXOXOXO", 2) == "XXXXXXXXXOOOOOOOOO"
    end
    @testset "encode with three rails" begin
        @test encode("WEAREDISCOVEREDFLEEATONCE", 3) == "WECRLTEERDSOEEFEAOCAIVDEN"
    end
    @testset "encode with ending in the middle" begin
        @test encode("EXERCISES", 4) == "ESXIEECSR"
    end
end

@testset "decode" begin
    @testset "decode with three rails" begin
        @test decode("TEITELHDVLSNHDTISEIIEA", 3) == "THEDEVILISINTHEDETAILS"
    end
    @testset "decode with five rails" begin
        @test decode("EIEXMSMESAORIWSCE", 5) == "EXERCISMISAWESOME"
    end
    @testset "decode with six rails" begin
        @test decode("133714114238148966225439541018335470986172518171757571896261", 6) == "112358132134558914423337761098715972584418167651094617711286"
    end
end

