# canonical data version: 2.1.0
# This file was generated by a script.

using Test

include("resistor-color-duo.jl")

@testset "Brown and black" begin
    @test value(["brown", "black"]) == 10
end

@testset "Blue and grey" begin
    @test value(["blue", "grey"]) == 68
end

@testset "Yellow and violet" begin
    @test value(["yellow", "violet"]) == 47
end

@testset "Orange and orange" begin
    @test value(["orange", "orange"]) == 33
end

@testset "Ignore additional colors" begin
    @test value(["green", "brown", "orange"]) == 51
end

