# canonical data version: 1.0.0
# This file was generated by a script.

using Test

include("resistor-color.jl")

@testset "Color codes" begin
    @testset "Black" begin
        @test color_code("black") == 0
    end
    @testset "White" begin
        @test color_code("white") == 9
    end
    @testset "Orange" begin
        @test color_code("orange") == 3
    end
end

@testset "Colors" begin
    @test colors() == ["black", "brown", "red", "orange", "yellow", "green", "blue", "violet", "grey", "white"]
end

