# canonical data version: 1.0.0
# This file was generated by a script.

using Test

include("resistor-color-trio.jl")

@testset "Orange and orange and black" begin
    @test label(["orange", "orange", "black"]) == Dict("value" => 33, "unit" => "ohms")
end

@testset "Blue and grey and brown" begin
    @test label(["blue", "grey", "brown"]) == Dict("value" => 680, "unit" => "ohms")
end

@testset "Red and black and red" begin
    @test label(["red", "black", "red"]) == Dict("value" => 2, "unit" => "kiloohms")
end

@testset "Green and brown and orange" begin
    @test label(["green", "brown", "orange"]) == Dict("value" => 51, "unit" => "kiloohms")
end

@testset "Yellow and violet and yellow" begin
    @test label(["yellow", "violet", "yellow"]) == Dict("value" => 470, "unit" => "kiloohms")
end

