# canonical data version: 1.2.0
# This file was generated by a script.

using Test

include("rotational-cipher.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# The tests are a series of rotation tests: 

@testset "Test rotation from English to ROTn" begin
    @testset "rotate a by 0, same output as input" begin
        @test rotate("a", 0) == "a"
    end
    @testset "rotate a by 1" begin
        @test rotate("a", 1) == "b"
    end
    @testset "rotate a by 26, same output as input" begin
        @test rotate("a", 26) == "a"
    end
    @testset "rotate m by 13" begin
        @test rotate("m", 13) == "z"
    end
    @testset "rotate n by 13 with wrap around alphabet" begin
        @test rotate("n", 13) == "a"
    end
    @testset "rotate capital letters" begin
        @test rotate("OMG", 5) == "TRL"
    end
    @testset "rotate spaces" begin
        @test rotate("O M G", 5) == "T R L"
    end
    @testset "rotate numbers" begin
        @test rotate("Testing 1 2 3 testing", 4) == "Xiwxmrk 1 2 3 xiwxmrk"
    end
    @testset "rotate punctuation" begin
        @test rotate("Let's eat, Grandma!", 21) == "Gzo'n zvo, Bmviyhv!"
    end
    @testset "rotate all letters" begin
        @test rotate("The quick brown fox jumps over the lazy dog.", 13) == "Gur dhvpx oebja sbk whzcf bire gur ynml qbt."
    end
end

