# canonical data version: 1.2.0
# This file was generated by a script.

using Test

include("say.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# An 'error' object is used as expected value to indicate that the
# input value is out of the range described in the exercise.

@testset "zero" begin
    @test say(0) == "zero"
end

@testset "one" begin
    @test say(1) == "one"
end

@testset "fourteen" begin
    @test say(14) == "fourteen"
end

@testset "twenty" begin
    @test say(20) == "twenty"
end

@testset "twenty-two" begin
    @test say(22) == "twenty-two"
end

@testset "one hundred" begin
    @test say(100) == "one hundred"
end

@testset "one hundred twenty-three" begin
    @test say(123) == "one hundred twenty-three"
end

@testset "one thousand" begin
    @test say(1000) == "one thousand"
end

@testset "one thousand two hundred thirty-four" begin
    @test say(1234) == "one thousand two hundred thirty-four"
end

@testset "one million" begin
    @test say(1000000) == "one million"
end

@testset "one million two thousand three hundred forty-five" begin
    @test say(1002345) == "one million two thousand three hundred forty-five"
end

@testset "one billion" begin
    @test say(1000000000) == "one billion"
end

@testset "a big number" begin
    @test say(987654321123) == "nine hundred eighty-seven billion six hundred fifty-four million three hundred twenty-one thousand one hundred twenty-three"
end

@testset "numbers below zero are out of range" begin
    @test_throws ArgumentError say(-1)
end

@testset "numbers above 999,999,999,999 are out of range" begin
    @test_throws ArgumentError say(1000000000000)
end

