# canonical data version: 2.0.0
# This file was generated by a script.

using Test

include("scale-generator.jl")

@testset "Chromatic scales" begin
    @testset "Chromatic scale with sharps" begin
        @test chromatic("C") == ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
    end
    @testset "Chromatic scale with flats" begin
        @test chromatic("F") == ["F", "Gb", "G", "Ab", "A", "Bb", "B", "C", "Db", "D", "Eb", "E"]
    end
end

@testset "Scales with specified intervals" begin
    @testset "Simple major scale" begin
        @test interval("C", "MMmMMMm") == ["C", "D", "E", "F", "G", "A", "B"]
    end
    @testset "Major scale with sharps" begin
        @test interval("G", "MMmMMMm") == ["G", "A", "B", "C", "D", "E", "F#"]
    end
    @testset "Major scale with flats" begin
        @test interval("F", "MMmMMMm") == ["F", "G", "A", "Bb", "C", "D", "E"]
    end
    @testset "Minor scale with sharps" begin
        @test interval("f#", "MmMMmMM") == ["F#", "G#", "A", "B", "C#", "D", "E"]
    end
    @testset "Minor scale with flats" begin
        @test interval("bb", "MmMMmMM") == ["Bb", "C", "Db", "Eb", "F", "Gb", "Ab"]
    end
    @testset "Dorian mode" begin
        @test interval("d", "MmMMMmM") == ["D", "E", "F", "G", "A", "B", "C"]
    end
    @testset "Mixolydian mode" begin
        @test interval("Eb", "MMmMMmM") == ["Eb", "F", "G", "Ab", "Bb", "C", "Db"]
    end
    @testset "Lydian mode" begin
        @test interval("a", "MMMmMMm") == ["A", "B", "C#", "D#", "E", "F#", "G#"]
    end
    @testset "Phrygian mode" begin
        @test interval("e", "mMMMmMM") == ["E", "F", "G", "A", "B", "C", "D"]
    end
    @testset "Locrian mode" begin
        @test interval("g", "mMMmMMM") == ["G", "Ab", "Bb", "C", "Db", "Eb", "F"]
    end
    @testset "Harmonic minor" begin
        @test interval("d", "MmMMmAm") == ["D", "E", "F", "G", "A", "Bb", "Db"]
    end
    @testset "Octatonic" begin
        @test interval("C", "MmMmMmMm") == ["C", "D", "D#", "F", "F#", "G#", "A", "B"]
    end
    @testset "Hexatonic" begin
        @test interval("Db", "MMMMMM") == ["Db", "Eb", "F", "G", "A", "B"]
    end
    @testset "Pentatonic" begin
        @test interval("A", "MMAMA") == ["A", "B", "C#", "E", "F#"]
    end
    @testset "Enigmatic" begin
        @test interval("G", "mAMMMmm") == ["G", "G#", "B", "C#", "D#", "F", "F#"]
    end
end

