# canonical data version: 1.5.0
# This file was generated by a script.

using Test

include("sum-of-multiples.jl")

@testset "no multiples within limit" begin
    @test sum([3, 5], 1) == 0
end

@testset "one factor has multiples within limit" begin
    @test sum([3, 5], 4) == 3
end

@testset "more than one multiple within limit" begin
    @test sum([3], 7) == 9
end

@testset "more than one factor with multiples within limit" begin
    @test sum([3, 5], 10) == 23
end

@testset "each multiple is only counted once" begin
    @test sum([3, 5], 100) == 2318
end

@testset "a much larger limit" begin
    @test sum([3, 5], 1000) == 233168
end

@testset "three factors" begin
    @test sum([7, 13, 17], 20) == 51
end

@testset "factors not relatively prime" begin
    @test sum([4, 6], 15) == 30
end

@testset "some pairs of factors relatively prime and some not" begin
    @test sum([5, 6, 8], 150) == 4419
end

@testset "one factor is a multiple of another" begin
    @test sum([5, 25], 51) == 275
end

@testset "much larger factors" begin
    @test sum([43, 47], 10000) == 2203160
end

@testset "all numbers are multiples of 1" begin
    @test sum([1], 100) == 4950
end

@testset "no factors means an empty sum" begin
    @test sum([], 10000) == 0
end

@testset "the only multiple of 0 is 0" begin
    @test sum([0], 1) == 0
end

@testset "the factor 0 does not affect the sum of multiples of other factors" begin
    @test sum([3, 0], 4) == 3
end

@testset "solutions using include-exclude must extend to cardinality greater than 3" begin
    @test sum([2, 3, 5, 7, 11], 10000) == 39614537
end

