# canonical data version: 1.4.0
# This file was generated by a script.

using Test

include("tournament.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# The inputs and outputs are represented as arrays of strings to
# improve readability in this JSON file.
# Your track may choose whether to present the input as a single
# string (concatenating all the lines) or as the list.
# In most cases, it seems to make sense to expect the output as
# a single string.

@testset "just the header if no input" begin
    @test tally([]) == ["Team                           | MP |  W |  D |  L |  P"]
end

@testset "a win is three points, a loss is zero points" begin
    @test tally(["Allegoric Alaskans;Blithering Badgers;win"]) == ["Team                           | MP |  W |  D |  L |  P", "Allegoric Alaskans             |  1 |  1 |  0 |  0 |  3", "Blithering Badgers             |  1 |  0 |  0 |  1 |  0"]
end

@testset "a win can also be expressed as a loss" begin
    @test tally(["Blithering Badgers;Allegoric Alaskans;loss"]) == ["Team                           | MP |  W |  D |  L |  P", "Allegoric Alaskans             |  1 |  1 |  0 |  0 |  3", "Blithering Badgers             |  1 |  0 |  0 |  1 |  0"]
end

@testset "a different team can win" begin
    @test tally(["Blithering Badgers;Allegoric Alaskans;win"]) == ["Team                           | MP |  W |  D |  L |  P", "Blithering Badgers             |  1 |  1 |  0 |  0 |  3", "Allegoric Alaskans             |  1 |  0 |  0 |  1 |  0"]
end

@testset "a draw is one point each" begin
    @test tally(["Allegoric Alaskans;Blithering Badgers;draw"]) == ["Team                           | MP |  W |  D |  L |  P", "Allegoric Alaskans             |  1 |  0 |  1 |  0 |  1", "Blithering Badgers             |  1 |  0 |  1 |  0 |  1"]
end

@testset "There can be more than one match" begin
    @test tally(["Allegoric Alaskans;Blithering Badgers;win", "Allegoric Alaskans;Blithering Badgers;win"]) == ["Team                           | MP |  W |  D |  L |  P", "Allegoric Alaskans             |  2 |  2 |  0 |  0 |  6", "Blithering Badgers             |  2 |  0 |  0 |  2 |  0"]
end

@testset "There can be more than one winner" begin
    @test tally(["Allegoric Alaskans;Blithering Badgers;loss", "Allegoric Alaskans;Blithering Badgers;win"]) == ["Team                           | MP |  W |  D |  L |  P", "Allegoric Alaskans             |  2 |  1 |  0 |  1 |  3", "Blithering Badgers             |  2 |  1 |  0 |  1 |  3"]
end

@testset "There can be more than two teams" begin
    @test tally(["Allegoric Alaskans;Blithering Badgers;win", "Blithering Badgers;Courageous Californians;win", "Courageous Californians;Allegoric Alaskans;loss"]) == ["Team                           | MP |  W |  D |  L |  P", "Allegoric Alaskans             |  2 |  2 |  0 |  0 |  6", "Blithering Badgers             |  2 |  1 |  0 |  1 |  3", "Courageous Californians        |  2 |  0 |  0 |  2 |  0"]
end

@testset "typical input" begin
    @test tally(["Allegoric Alaskans;Blithering Badgers;win", "Devastating Donkeys;Courageous Californians;draw", "Devastating Donkeys;Allegoric Alaskans;win", "Courageous Californians;Blithering Badgers;loss", "Blithering Badgers;Devastating Donkeys;loss", "Allegoric Alaskans;Courageous Californians;win"]) == ["Team                           | MP |  W |  D |  L |  P", "Devastating Donkeys            |  3 |  2 |  1 |  0 |  7", "Allegoric Alaskans             |  3 |  2 |  0 |  1 |  6", "Blithering Badgers             |  3 |  1 |  0 |  2 |  3", "Courageous Californians        |  3 |  0 |  1 |  2 |  1"]
end

@testset "incomplete competition (not all pairs have played)" begin
    @test tally(["Allegoric Alaskans;Blithering Badgers;loss", "Devastating Donkeys;Allegoric Alaskans;loss", "Courageous Californians;Blithering Badgers;draw", "Allegoric Alaskans;Courageous Californians;win"]) == ["Team                           | MP |  W |  D |  L |  P", "Allegoric Alaskans             |  3 |  2 |  0 |  1 |  6", "Blithering Badgers             |  2 |  1 |  1 |  0 |  4", "Courageous Californians        |  2 |  0 |  1 |  1 |  1", "Devastating Donkeys            |  1 |  0 |  0 |  1 |  0"]
end

@testset "ties broken alphabetically" begin
    @test tally(["Courageous Californians;Devastating Donkeys;win", "Allegoric Alaskans;Blithering Badgers;win", "Devastating Donkeys;Allegoric Alaskans;loss", "Courageous Californians;Blithering Badgers;win", "Blithering Badgers;Devastating Donkeys;draw", "Allegoric Alaskans;Courageous Californians;draw"]) == ["Team                           | MP |  W |  D |  L |  P", "Allegoric Alaskans             |  3 |  2 |  1 |  0 |  7", "Courageous Californians        |  3 |  2 |  1 |  0 |  7", "Blithering Badgers             |  3 |  0 |  1 |  2 |  1", "Devastating Donkeys            |  3 |  0 |  1 |  2 |  1"]
end

