# canonical data version: 1.1.0
# This file was generated by a script.

using Test

include("transpose.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# JSON doesn't allow for multi-line strings, so all multi-line input is 
# presented here as arrays of strings. It's up to the test generator to join the 
# lines together with line breaks.

@testset "empty string" begin
    @test transpose([]) == []
end

@testset "two characters in a row" begin
    @test transpose(["A1"]) == ["A", "1"]
end

@testset "two characters in a column" begin
    @test transpose(["A", "1"]) == ["A1"]
end

@testset "simple" begin
    @test transpose(["ABC", "123"]) == ["A1", "B2", "C3"]
end

@testset "single line" begin
    @test transpose(["Single line."]) == ["S", "i", "n", "g", "l", "e", " ", "l", "i", "n", "e", "."]
end

@testset "first line longer than second line" begin
    @test transpose(["The fourth line.", "The fifth line."]) == ["TT", "hh", "ee", "  ", "ff", "oi", "uf", "rt", "th", "h ", " l", "li", "in", "ne", "e.", "."]
end

@testset "second line longer than first line" begin
    @test transpose(["The first line.", "The second line."]) == ["TT", "hh", "ee", "  ", "fs", "ie", "rc", "so", "tn", " d", "l ", "il", "ni", "en", ".e", " ."]
end

@testset "mixed line length" begin
    @test transpose(["The longest line.", "A long line.", "A longer line.", "A line."]) == ["TAAA", "h   ", "elll", " ooi", "lnnn", "ogge", "n e.", "glr", "ei ", "snl", "tei", " .n", "l e", "i .", "n", "e", "."]
end

@testset "square" begin
    @test transpose(["HEART", "EMBER", "ABUSE", "RESIN", "TREND"]) == ["HEART", "EMBER", "ABUSE", "RESIN", "TREND"]
end

@testset "rectangle" begin
    @test transpose(["FRACTURE", "OUTLINED", "BLOOMING", "SEPTETTE"]) == ["FOBS", "RULE", "ATOP", "CLOT", "TIME", "UNIT", "RENT", "EDGE"]
end

@testset "triangle" begin
    @test transpose(["T", "EE", "AAA", "SSSS", "EEEEE", "RRRRRR"]) == ["TEASER", " EASER", "  ASER", "   SER", "    ER", "     R"]
end

