# canonical data version: 2.0.0
# This file was generated by a script.

using Test

include("affine-cipher.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# The test are divided into two groups: 
# * Encoding from English to affine cipher
# * Decoding from affine cipher to all-lowercase-mashed-together English

@testset "encode" begin
    @testset "encode yes" begin
        @test encode("yes", Dict("a" => 5, "b" => 7)) == "xbt"
    end
    @testset "encode no" begin
        @test encode("no", Dict("a" => 15, "b" => 18)) == "fu"
    end
    @testset "encode OMG" begin
        @test encode("OMG", Dict("a" => 21, "b" => 3)) == "lvz"
    end
    @testset "encode O M G" begin
        @test encode("O M G", Dict("a" => 25, "b" => 47)) == "hjp"
    end
    @testset "encode mindblowingly" begin
        @test encode("mindblowingly", Dict("a" => 11, "b" => 15)) == "rzcwa gnxzc dgt"
    end
    @testset "encode numbers" begin
        @test encode("Testing,1 2 3, testing.", Dict("a" => 3, "b" => 4)) == "jqgjc rw123 jqgjc rw"
    end
    @testset "encode deep thought" begin
        @test encode("Truth is fiction.", Dict("a" => 5, "b" => 17)) == "iynia fdqfb ifje"
    end
    @testset "encode all the letters" begin
        @test encode("The quick brown fox jumps over the lazy dog.", Dict("a" => 17, "b" => 33)) == "swxtj npvyk lruol iejdc blaxk swxmh qzglf"
    end
    @testset "encode with a not coprime to m" begin
        @test_throws ArgumentError encode("This is a test.", Dict("a" => 6, "b" => 17))
    end
end

@testset "decode" begin
    @testset "decode exercism" begin
        @test decode("tytgn fjr", Dict("a" => 3, "b" => 7)) == "exercism"
    end
    @testset "decode a sentence" begin
        @test decode("qdwju nqcro muwhn odqun oppmd aunwd o", Dict("a" => 19, "b" => 16)) == "anobstacleisoftenasteppingstone"
    end
    @testset "decode numbers" begin
        @test decode("odpoz ub123 odpoz ub", Dict("a" => 25, "b" => 7)) == "testing123testing"
    end
    @testset "decode all the letters" begin
        @test decode("swxtj npvyk lruol iejdc blaxk swxmh qzglf", Dict("a" => 17, "b" => 33)) == "thequickbrownfoxjumpsoverthelazydog"
    end
    @testset "decode with no spaces in input" begin
        @test decode("swxtjnpvyklruoliejdcblaxkswxmhqzglf", Dict("a" => 17, "b" => 33)) == "thequickbrownfoxjumpsoverthelazydog"
    end
    @testset "decode with too many spaces" begin
        @test decode("vszzm    cly   yd cg    qdp", Dict("a" => 15, "b" => 16)) == "jollygreengiant"
    end
    @testset "decode with a not coprime to m" begin
        @test_throws ArgumentError decode("Test", Dict("a" => 13, "b" => 5))
    end
end

