# canonical data version: 1.1.0
# This file was generated by a script.

using Test

include("armstrong-numbers.jl")

@testset "Zero is an Armstrong number" begin
    @test is_armstrong_number(0) == true
end

@testset "Single digit numbers are Armstrong numbers" begin
    @test is_armstrong_number(5) == true
end

@testset "There are no 2 digit Armstrong numbers" begin
    @test is_armstrong_number(10) == false
end

@testset "Three digit number that is an Armstrong number" begin
    @test is_armstrong_number(153) == true
end

@testset "Three digit number that is not an Armstrong number" begin
    @test is_armstrong_number(100) == false
end

@testset "Four digit number that is an Armstrong number" begin
    @test is_armstrong_number(9474) == true
end

@testset "Four digit number that is not an Armstrong number" begin
    @test is_armstrong_number(9475) == false
end

@testset "Seven digit number that is an Armstrong number" begin
    @test is_armstrong_number(9926315) == true
end

@testset "Seven digit number that is not an Armstrong number" begin
    @test is_armstrong_number(9926314) == false
end

