# canonical data version: 1.3.0
# This file was generated by a script.

using Test

include("binary-search.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# The error object is used to indicate that the value is not included in the array.
# It should be replaced with the respective expression that is idiomatic
# for the language that implements the tests.
# Following https://github.com/exercism/problem-specifications/issues/234 the exercise
# should NOT include checking whether the array is sorted as it defeats
# the point of the binary search.
# The exercise should utilize an array-like (i.e. constant-time indexed)
# data structure and not a linked list. If something like an array is not
# usually used in the language the problem should not be implemented.
# See https://github.com/exercism/problem-specifications/issues/244 for details.

@testset "finds a value in an array with one element" begin
    @test find([6], 6) == 0
end

@testset "finds a value in the middle of an array" begin
    @test find([1, 3, 4, 6, 8, 9, 11], 6) == 3
end

@testset "finds a value at the beginning of an array" begin
    @test find([1, 3, 4, 6, 8, 9, 11], 1) == 0
end

@testset "finds a value at the end of an array" begin
    @test find([1, 3, 4, 6, 8, 9, 11], 11) == 6
end

@testset "finds a value in an array of odd length" begin
    @test find([1, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 634], 144) == 9
end

@testset "finds a value in an array of even length" begin
    @test find([1, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377], 21) == 5
end

@testset "identifies that a value is not included in the array" begin
    @test_throws ArgumentError find([1, 3, 4, 6, 8, 9, 11], 7)
end

@testset "a value smaller than the array's smallest value is not found" begin
    @test_throws ArgumentError find([1, 3, 4, 6, 8, 9, 11], 0)
end

@testset "a value larger than the array's largest value is not found" begin
    @test_throws ArgumentError find([1, 3, 4, 6, 8, 9, 11], 13)
end

@testset "nothing is found in an empty array" begin
    @test_throws ArgumentError find([], 1)
end

@testset "nothing is found when the left and right bounds cross" begin
    @test_throws ArgumentError find([1, 2], 0)
end

