# canonical data version: 1.6.0
# This file was generated by a script.

using Test

include("bob.jl")

@testset "stating something" begin
    @test response("Tom-ay-to, tom-aaaah-to.") == "Whatever."
end

@testset "shouting" begin
    @test response("WATCH OUT!") == "Whoa, chill out!"
end

@testset "shouting gibberish" begin
    @test response("FCECDFCAAB") == "Whoa, chill out!"
end

@testset "asking a question" begin
    @test response("Does this cryogenic chamber make me look fat?") == "Sure."
end

@testset "asking a numeric question" begin
    @test response("You are, what, like 15?") == "Sure."
end

@testset "asking gibberish" begin
    @test response("fffbbcbeab?") == "Sure."
end

@testset "talking forcefully" begin
    @test response("Hi there!") == "Whatever."
end

@testset "using acronyms in regular speech" begin
    @test response("It's OK if you don't want to go work for NASA.") == "Whatever."
end

@testset "forceful question" begin
    @test response("WHAT'S GOING ON?") == "Calm down, I know what I'm doing!"
end

@testset "shouting numbers" begin
    @test response("1, 2, 3 GO!") == "Whoa, chill out!"
end

@testset "no letters" begin
    @test response("1, 2, 3") == "Whatever."
end

@testset "question with no letters" begin
    @test response("4?") == "Sure."
end

@testset "shouting with special characters" begin
    @test response("ZOMG THE %^*@#\$(*^ ZOMBIES ARE COMING!!11!!1!") == "Whoa, chill out!"
end

@testset "shouting with no exclamation mark" begin
    @test response("I HATE THE DENTIST") == "Whoa, chill out!"
end

@testset "statement containing question mark" begin
    @test response("Ending with ? means a question.") == "Whatever."
end

@testset "non-letters with question" begin
    @test response(":) ?") == "Sure."
end

@testset "prattling on" begin
    @test response("Wait! Hang on. Are you going to be OK?") == "Sure."
end

@testset "silence" begin
    @test response("") == "Fine. Be that way!"
end

@testset "prolonged silence" begin
    @test response("          ") == "Fine. Be that way!"
end

@testset "alternate silence" begin
    @test response("\t\t\t\t\t\t\t\t\t\t") == "Fine. Be that way!"
end

@testset "multiple line question" begin
    @test response("\nDoes this cryogenic chamber make me look fat?\nNo.") == "Whatever."
end

@testset "starting with whitespace" begin
    @test response("         hmmmmmmm...") == "Whatever."
end

@testset "ending with whitespace" begin
    @test response("Okay if like my  spacebar  quite a bit?   ") == "Sure."
end

@testset "other whitespace" begin
    @test response("\n\r \t") == "Fine. Be that way!"
end

@testset "non-question ending with whitespace" begin
    @test response("This is a statement ending with whitespace      ") == "Whatever."
end

