# canonical data version: 1.2.1
# This file was generated by a script.

using Test

include("collatz-conjecture.jl")

@testset "zero steps for one" begin
    @test steps(1) == 0
end

@testset "divide if even" begin
    @test steps(16) == 4
end

@testset "even and odd steps" begin
    @test steps(12) == 9
end

@testset "large number of even and odd steps" begin
    @test steps(1000000) == 152
end

@testset "zero is an error" begin
    @test_throws ArgumentError steps(0)
end

@testset "negative value is an error" begin
    @test_throws ArgumentError steps(-15)
end

