# canonical data version: 1.2.0
# This file was generated by a script.

using Test

include("difference-of-squares.jl")

@testset "Square the sum of the numbers up to the given number" begin
    @testset "square of sum 1" begin
        @test square_of_sum(1) == 1
    end
    @testset "square of sum 5" begin
        @test square_of_sum(5) == 225
    end
    @testset "square of sum 100" begin
        @test square_of_sum(100) == 25502500
    end
end

@testset "Sum the squares of the numbers up to the given number" begin
    @testset "sum of squares 1" begin
        @test sum_of_squares(1) == 1
    end
    @testset "sum of squares 5" begin
        @test sum_of_squares(5) == 55
    end
    @testset "sum of squares 100" begin
        @test sum_of_squares(100) == 338350
    end
end

@testset "Subtract sum of squares from square of sums" begin
    @testset "difference of squares 1" begin
        @test difference_of_squares(1) == 0
    end
    @testset "difference of squares 5" begin
        @test difference_of_squares(5) == 170
    end
    @testset "difference of squares 100" begin
        @test difference_of_squares(100) == 25164150
    end
end

