# canonical data version: 2.0.0
# This file was generated by a script.

using Test

include("gigasecond.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# The basic test is to add one gigasecond to a few ordinary dates.
# Most test programs currently check only the date and ignore the time.
# For languages with a native date-time type though, expected times
# here show the correct seconds, ignoring leap seconds.
# The date and time formats here are per
# http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15.
# 
# Finally, as a demonstration but not really a test,
# some languages demonstrate the add function by inviting the
# solver to include their birthdate in either the solution code
# or test program.  The test program then shows or tests their
# gigasecond anniversary.

@testset "Add one gigasecond to the input." begin
    @testset "date only specification of time" begin
        @test add("2011-04-25") == "2043-01-01T01:46:40"
    end
    @testset "second test for date only specification of time" begin
        @test add("1977-06-13") == "2009-02-19T01:46:40"
    end
    @testset "third test for date only specification of time" begin
        @test add("1959-07-19") == "1991-03-27T01:46:40"
    end
    @testset "full time specified" begin
        @test add("2015-01-24T22:00:00") == "2046-10-02T23:46:40"
    end
    @testset "full time with day roll-over" begin
        @test add("2015-01-24T23:59:59") == "2046-10-03T01:46:39"
    end
end

