# canonical data version: 1.2.0
# This file was generated by a script.

using Test

include("grains.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# The final tests of square test error conditions
# In these cases you should expect an error as is idiomatic for your language

@testset "returns the number of grains on the square" begin
    @testset "1" begin
        @test square(1) == 1
    end
    @testset "2" begin
        @test square(2) == 2
    end
    @testset "3" begin
        @test square(3) == 4
    end
    @testset "4" begin
        @test square(4) == 8
    end
    @testset "16" begin
        @test square(16) == 32768
    end
    @testset "32" begin
        @test square(32) == 2147483648
    end
    @testset "64" begin
        @test square(64) == -9223372036854775808
    end
    @testset "square 0 raises an exception" begin
        @test_throws ArgumentError square(0)
    end
    @testset "negative square raises an exception" begin
        @test_throws ArgumentError square(-1)
    end
    @testset "square greater than 64 raises an exception" begin
        @test_throws ArgumentError square(65)
    end
end

@testset "returns the total number of grains on the board" begin
    @test total() == -1
end

