# canonical data version: 2.3.0
# This file was generated by a script.

using Test

include("hamming.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# Language implementations vary on the issue of unequal length strands.
# A language may elect to simplify this task by only presenting equal
# length test cases.  For languages handling unequal length strands as
# error condition, unequal length test cases are included here and are
# indicated with an error object.  Language idioms of errors or exceptions
# should be followed.  Alternative interpretations such as ignoring excess
# length at the end are not represented here.

@testset "empty strands" begin
    @test distance("", "") == 0
end

@testset "single letter identical strands" begin
    @test distance("A", "A") == 0
end

@testset "single letter different strands" begin
    @test distance("G", "T") == 1
end

@testset "long identical strands" begin
    @test distance("GGACTGAAATCTG", "GGACTGAAATCTG") == 0
end

@testset "long different strands" begin
    @test distance("GGACGGATTCTG", "AGGACGGATTCT") == 9
end

@testset "disallow first strand longer" begin
    @test_throws ArgumentError distance("AATG", "AAA")
end

@testset "disallow second strand longer" begin
    @test_throws ArgumentError distance("ATA", "AGTG")
end

@testset "disallow left empty strand" begin
    @test_throws ArgumentError distance("", "G")
end

@testset "disallow right empty strand" begin
    @test_throws ArgumentError distance("G", "")
end

