# canonical data version: 4.0.0
# This file was generated by a script.

using Test

include("high-scores.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# This is meant to be an easy exercise to practise: 
# * arrays as simple lists
# * instantiating a class
# Consider adding a track specific recommendation in the track's hint.md.
# Consider linking to a explanatory blogpost or beginner level tutorials for both topics.
# See Ruby Track hint.md for an example.

@testset "List of scores" begin
    @test scores([30, 50, 20, 70]) == [30, 50, 20, 70]
end

@testset "Latest score" begin
    @test latest([100, 0, 90, 30]) == 30
end

@testset "Personal best" begin
    @test personal_best([40, 100, 70]) == 100
end

@testset "Top 3 scores" begin
    @testset "Personal top three from a list of scores" begin
        @test personal_top_three([10, 30, 90, 30, 100, 20, 10, 0, 30, 40, 40, 70, 70]) == [100, 90, 70]
    end
    @testset "Personal top highest to lowest" begin
        @test personal_top_three([20, 10, 30]) == [30, 20, 10]
    end
    @testset "Personal top when there is a tie" begin
        @test personal_top_three([40, 20, 40, 30]) == [40, 40, 30]
    end
    @testset "Personal top when there are less than 3" begin
        @test personal_top_three([30, 70]) == [70, 30]
    end
    @testset "Personal top when there is only one" begin
        @test personal_top_three([40]) == [40]
    end
end

