# canonical data version: 1.0.0
# This file was generated by a script.

using Test

include("knapsack.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# Depending on the language, the input type can be modified

@testset "no items" begin
    @test maximum_value(100, Dict()) == 0
end

@testset "one item, too heavy" begin
    @test maximum_value(10, [Dict("weight" => 100, "value" => 1)]) == 0
end

@testset "five items (cannot be greedy by weight)" begin
    @test maximum_value(10, [Dict("weight" => 2, "value" => 5), Dict("weight" => 2, "value" => 5), Dict("weight" => 2, "value" => 5), Dict("weight" => 2, "value" => 5), Dict("weight" => 10, "value" => 21)]) == 21
end

@testset "five items (cannot be greedy by value)" begin
    @test maximum_value(10, [Dict("weight" => 2, "value" => 20), Dict("weight" => 2, "value" => 20), Dict("weight" => 2, "value" => 20), Dict("weight" => 2, "value" => 20), Dict("weight" => 10, "value" => 50)]) == 80
end

@testset "example knapsack" begin
    @test maximum_value(10, [Dict("weight" => 5, "value" => 10), Dict("weight" => 4, "value" => 40), Dict("weight" => 6, "value" => 30), Dict("weight" => 4, "value" => 50)]) == 90
end

@testset "8 items" begin
    @test maximum_value(104, [Dict("weight" => 25, "value" => 350), Dict("weight" => 35, "value" => 400), Dict("weight" => 45, "value" => 450), Dict("weight" => 5, "value" => 20), Dict("weight" => 25, "value" => 70), Dict("weight" => 3, "value" => 8), Dict("weight" => 2, "value" => 5), Dict("weight" => 2, "value" => 5)]) == 900
end

@testset "15 items" begin
    @test maximum_value(750, [Dict("weight" => 70, "value" => 135), Dict("weight" => 73, "value" => 139), Dict("weight" => 77, "value" => 149), Dict("weight" => 80, "value" => 150), Dict("weight" => 82, "value" => 156), Dict("weight" => 87, "value" => 163), Dict("weight" => 90, "value" => 173), Dict("weight" => 94, "value" => 184), Dict("weight" => 98, "value" => 192), Dict("weight" => 106, "value" => 201), Dict("weight" => 110, "value" => 210), Dict("weight" => 113, "value" => 214), Dict("weight" => 115, "value" => 221), Dict("weight" => 118, "value" => 229), Dict("weight" => 120, "value" => 240)]) == 1458
end

