# canonical data version: 1.6.0
# This file was generated by a script.

using Test

include("leap.jl")

@testset "year not divisible by 4 in common year" begin
    @test leap_year(2015) == false
end

@testset "year divisible by 2, not divisible by 4 in common year" begin
    @test leap_year(1970) == false
end

@testset "year divisible by 4, not divisible by 100 in leap year" begin
    @test leap_year(1996) == true
end

@testset "year divisible by 4 and 5 is still a leap year" begin
    @test leap_year(1960) == true
end

@testset "year divisible by 100, not divisible by 400 in common year" begin
    @test leap_year(2100) == false
end

@testset "year divisible by 100 but not by 3 is still not a leap year" begin
    @test leap_year(1900) == false
end

@testset "year divisible by 400 in leap year" begin
    @test leap_year(2000) == true
end

@testset "year divisible by 400 but not by 125 is still a leap year" begin
    @test leap_year(2400) == true
end

@testset "year divisible by 200, not divisible by 400 in common year" begin
    @test leap_year(1800) == false
end

