# canonical data version: 1.7.0
# This file was generated by a script.

using Test

include("luhn.jl")

@testset "single digit strings can not be valid" begin
    @test valid("1") == false
end

@testset "a single zero is invalid" begin
    @test valid("0") == false
end

@testset "a simple valid SIN that remains valid if reversed" begin
    @test valid("059") == true
end

@testset "a simple valid SIN that becomes invalid if reversed" begin
    @test valid("59") == true
end

@testset "a valid Canadian SIN" begin
    @test valid("055 444 285") == true
end

@testset "invalid Canadian SIN" begin
    @test valid("055 444 286") == false
end

@testset "invalid credit card" begin
    @test valid("8273 1232 7352 0569") == false
end

@testset "invalid long number with an even remainder" begin
    @test valid("1 2345 6789 1234 5678 9012") == false
end

@testset "valid number with an even number of digits" begin
    @test valid("095 245 88") == true
end

@testset "valid number with an odd number of spaces" begin
    @test valid("234 567 891 234") == true
end

@testset "valid strings with a non-digit added at the end become invalid" begin
    @test valid("059a") == false
end

@testset "valid strings with punctuation included become invalid" begin
    @test valid("055-444-285") == false
end

@testset "valid strings with symbols included become invalid" begin
    @test valid("055# 444\$ 285") == false
end

@testset "single zero with space is invalid" begin
    @test valid(" 0") == false
end

@testset "more than a single zero is valid" begin
    @test valid("0000 0") == true
end

@testset "input digit 9 is correctly converted to output digit 9" begin
    @test valid("091") == true
end

@testset "using ascii value for non-doubled non-digit isn't allowed" begin
    @test valid("055b 444 285") == false
end

@testset "using ascii value for doubled non-digit isn't allowed" begin
    @test valid(":9") == false
end

