# canonical data version: 1.3.0
# This file was generated by a script.

using Test

include("matrix.jl")

@testset "extract row from one number matrix" begin
    @test row("1", 1) == [1]
end

@testset "can extract row" begin
    @test row("1 2\n3 4", 2) == [3, 4]
end

@testset "extract row where numbers have different widths" begin
    @test row("1 2\n10 20", 2) == [10, 20]
end

@testset "can extract row from non-square matrix with no corresponding column" begin
    @test row("1 2 3\n4 5 6\n7 8 9\n8 7 6", 4) == [8, 7, 6]
end

@testset "extract column from one number matrix" begin
    @test column("1", 1) == [1]
end

@testset "can extract column" begin
    @test column("1 2 3\n4 5 6\n7 8 9", 3) == [3, 6, 9]
end

@testset "can extract column from non-square matrix with no corresponding row" begin
    @test column("1 2 3 4\n5 6 7 8\n9 8 7 6", 4) == [4, 8, 6]
end

@testset "extract column where numbers have different widths" begin
    @test column("89 1903 3\n18 3 1\n9 4 800", 2) == [1903, 3, 4]
end

