# canonical data version: 1.1.0
# This file was generated by a script.

using Test

include("meetup.jl")

@testset "monteenth of May 2013" begin
    @test meetup(2013, 5, "teenth", "Monday") == "2013-05-13"
end

@testset "monteenth of August 2013" begin
    @test meetup(2013, 8, "teenth", "Monday") == "2013-08-19"
end

@testset "monteenth of September 2013" begin
    @test meetup(2013, 9, "teenth", "Monday") == "2013-09-16"
end

@testset "tuesteenth of March 2013" begin
    @test meetup(2013, 3, "teenth", "Tuesday") == "2013-03-19"
end

@testset "tuesteenth of April 2013" begin
    @test meetup(2013, 4, "teenth", "Tuesday") == "2013-04-16"
end

@testset "tuesteenth of August 2013" begin
    @test meetup(2013, 8, "teenth", "Tuesday") == "2013-08-13"
end

@testset "wednesteenth of January 2013" begin
    @test meetup(2013, 1, "teenth", "Wednesday") == "2013-01-16"
end

@testset "wednesteenth of February 2013" begin
    @test meetup(2013, 2, "teenth", "Wednesday") == "2013-02-13"
end

@testset "wednesteenth of June 2013" begin
    @test meetup(2013, 6, "teenth", "Wednesday") == "2013-06-19"
end

@testset "thursteenth of May 2013" begin
    @test meetup(2013, 5, "teenth", "Thursday") == "2013-05-16"
end

@testset "thursteenth of June 2013" begin
    @test meetup(2013, 6, "teenth", "Thursday") == "2013-06-13"
end

@testset "thursteenth of September 2013" begin
    @test meetup(2013, 9, "teenth", "Thursday") == "2013-09-19"
end

@testset "friteenth of April 2013" begin
    @test meetup(2013, 4, "teenth", "Friday") == "2013-04-19"
end

@testset "friteenth of August 2013" begin
    @test meetup(2013, 8, "teenth", "Friday") == "2013-08-16"
end

@testset "friteenth of September 2013" begin
    @test meetup(2013, 9, "teenth", "Friday") == "2013-09-13"
end

@testset "saturteenth of February 2013" begin
    @test meetup(2013, 2, "teenth", "Saturday") == "2013-02-16"
end

@testset "saturteenth of April 2013" begin
    @test meetup(2013, 4, "teenth", "Saturday") == "2013-04-13"
end

@testset "saturteenth of October 2013" begin
    @test meetup(2013, 10, "teenth", "Saturday") == "2013-10-19"
end

@testset "sunteenth of May 2013" begin
    @test meetup(2013, 5, "teenth", "Sunday") == "2013-05-19"
end

@testset "sunteenth of June 2013" begin
    @test meetup(2013, 6, "teenth", "Sunday") == "2013-06-16"
end

@testset "sunteenth of October 2013" begin
    @test meetup(2013, 10, "teenth", "Sunday") == "2013-10-13"
end

@testset "first Monday of March 2013" begin
    @test meetup(2013, 3, "first", "Monday") == "2013-03-04"
end

@testset "first Monday of April 2013" begin
    @test meetup(2013, 4, "first", "Monday") == "2013-04-01"
end

@testset "first Tuesday of May 2013" begin
    @test meetup(2013, 5, "first", "Tuesday") == "2013-05-07"
end

@testset "first Tuesday of June 2013" begin
    @test meetup(2013, 6, "first", "Tuesday") == "2013-06-04"
end

@testset "first Wednesday of July 2013" begin
    @test meetup(2013, 7, "first", "Wednesday") == "2013-07-03"
end

@testset "first Wednesday of August 2013" begin
    @test meetup(2013, 8, "first", "Wednesday") == "2013-08-07"
end

@testset "first Thursday of September 2013" begin
    @test meetup(2013, 9, "first", "Thursday") == "2013-09-05"
end

@testset "first Thursday of October 2013" begin
    @test meetup(2013, 10, "first", "Thursday") == "2013-10-03"
end

@testset "first Friday of November 2013" begin
    @test meetup(2013, 11, "first", "Friday") == "2013-11-01"
end

@testset "first Friday of December 2013" begin
    @test meetup(2013, 12, "first", "Friday") == "2013-12-06"
end

@testset "first Saturday of January 2013" begin
    @test meetup(2013, 1, "first", "Saturday") == "2013-01-05"
end

@testset "first Saturday of February 2013" begin
    @test meetup(2013, 2, "first", "Saturday") == "2013-02-02"
end

@testset "first Sunday of March 2013" begin
    @test meetup(2013, 3, "first", "Sunday") == "2013-03-03"
end

@testset "first Sunday of April 2013" begin
    @test meetup(2013, 4, "first", "Sunday") == "2013-04-07"
end

@testset "second Monday of March 2013" begin
    @test meetup(2013, 3, "second", "Monday") == "2013-03-11"
end

@testset "second Monday of April 2013" begin
    @test meetup(2013, 4, "second", "Monday") == "2013-04-08"
end

@testset "second Tuesday of May 2013" begin
    @test meetup(2013, 5, "second", "Tuesday") == "2013-05-14"
end

@testset "second Tuesday of June 2013" begin
    @test meetup(2013, 6, "second", "Tuesday") == "2013-06-11"
end

@testset "second Wednesday of July 2013" begin
    @test meetup(2013, 7, "second", "Wednesday") == "2013-07-10"
end

@testset "second Wednesday of August 2013" begin
    @test meetup(2013, 8, "second", "Wednesday") == "2013-08-14"
end

@testset "second Thursday of September 2013" begin
    @test meetup(2013, 9, "second", "Thursday") == "2013-09-12"
end

@testset "second Thursday of October 2013" begin
    @test meetup(2013, 10, "second", "Thursday") == "2013-10-10"
end

@testset "second Friday of November 2013" begin
    @test meetup(2013, 11, "second", "Friday") == "2013-11-08"
end

@testset "second Friday of December 2013" begin
    @test meetup(2013, 12, "second", "Friday") == "2013-12-13"
end

@testset "second Saturday of January 2013" begin
    @test meetup(2013, 1, "second", "Saturday") == "2013-01-12"
end

@testset "second Saturday of February 2013" begin
    @test meetup(2013, 2, "second", "Saturday") == "2013-02-09"
end

@testset "second Sunday of March 2013" begin
    @test meetup(2013, 3, "second", "Sunday") == "2013-03-10"
end

@testset "second Sunday of April 2013" begin
    @test meetup(2013, 4, "second", "Sunday") == "2013-04-14"
end

@testset "third Monday of March 2013" begin
    @test meetup(2013, 3, "third", "Monday") == "2013-03-18"
end

@testset "third Monday of April 2013" begin
    @test meetup(2013, 4, "third", "Monday") == "2013-04-15"
end

@testset "third Tuesday of May 2013" begin
    @test meetup(2013, 5, "third", "Tuesday") == "2013-05-21"
end

@testset "third Tuesday of June 2013" begin
    @test meetup(2013, 6, "third", "Tuesday") == "2013-06-18"
end

@testset "third Wednesday of July 2013" begin
    @test meetup(2013, 7, "third", "Wednesday") == "2013-07-17"
end

@testset "third Wednesday of August 2013" begin
    @test meetup(2013, 8, "third", "Wednesday") == "2013-08-21"
end

@testset "third Thursday of September 2013" begin
    @test meetup(2013, 9, "third", "Thursday") == "2013-09-19"
end

@testset "third Thursday of October 2013" begin
    @test meetup(2013, 10, "third", "Thursday") == "2013-10-17"
end

@testset "third Friday of November 2013" begin
    @test meetup(2013, 11, "third", "Friday") == "2013-11-15"
end

@testset "third Friday of December 2013" begin
    @test meetup(2013, 12, "third", "Friday") == "2013-12-20"
end

@testset "third Saturday of January 2013" begin
    @test meetup(2013, 1, "third", "Saturday") == "2013-01-19"
end

@testset "third Saturday of February 2013" begin
    @test meetup(2013, 2, "third", "Saturday") == "2013-02-16"
end

@testset "third Sunday of March 2013" begin
    @test meetup(2013, 3, "third", "Sunday") == "2013-03-17"
end

@testset "third Sunday of April 2013" begin
    @test meetup(2013, 4, "third", "Sunday") == "2013-04-21"
end

@testset "fourth Monday of March 2013" begin
    @test meetup(2013, 3, "fourth", "Monday") == "2013-03-25"
end

@testset "fourth Monday of April 2013" begin
    @test meetup(2013, 4, "fourth", "Monday") == "2013-04-22"
end

@testset "fourth Tuesday of May 2013" begin
    @test meetup(2013, 5, "fourth", "Tuesday") == "2013-05-28"
end

@testset "fourth Tuesday of June 2013" begin
    @test meetup(2013, 6, "fourth", "Tuesday") == "2013-06-25"
end

@testset "fourth Wednesday of July 2013" begin
    @test meetup(2013, 7, "fourth", "Wednesday") == "2013-07-24"
end

@testset "fourth Wednesday of August 2013" begin
    @test meetup(2013, 8, "fourth", "Wednesday") == "2013-08-28"
end

@testset "fourth Thursday of September 2013" begin
    @test meetup(2013, 9, "fourth", "Thursday") == "2013-09-26"
end

@testset "fourth Thursday of October 2013" begin
    @test meetup(2013, 10, "fourth", "Thursday") == "2013-10-24"
end

@testset "fourth Friday of November 2013" begin
    @test meetup(2013, 11, "fourth", "Friday") == "2013-11-22"
end

@testset "fourth Friday of December 2013" begin
    @test meetup(2013, 12, "fourth", "Friday") == "2013-12-27"
end

@testset "fourth Saturday of January 2013" begin
    @test meetup(2013, 1, "fourth", "Saturday") == "2013-01-26"
end

@testset "fourth Saturday of February 2013" begin
    @test meetup(2013, 2, "fourth", "Saturday") == "2013-02-23"
end

@testset "fourth Sunday of March 2013" begin
    @test meetup(2013, 3, "fourth", "Sunday") == "2013-03-24"
end

@testset "fourth Sunday of April 2013" begin
    @test meetup(2013, 4, "fourth", "Sunday") == "2013-04-28"
end

@testset "last Monday of March 2013" begin
    @test meetup(2013, 3, "last", "Monday") == "2013-03-25"
end

@testset "last Monday of April 2013" begin
    @test meetup(2013, 4, "last", "Monday") == "2013-04-29"
end

@testset "last Tuesday of May 2013" begin
    @test meetup(2013, 5, "last", "Tuesday") == "2013-05-28"
end

@testset "last Tuesday of June 2013" begin
    @test meetup(2013, 6, "last", "Tuesday") == "2013-06-25"
end

@testset "last Wednesday of July 2013" begin
    @test meetup(2013, 7, "last", "Wednesday") == "2013-07-31"
end

@testset "last Wednesday of August 2013" begin
    @test meetup(2013, 8, "last", "Wednesday") == "2013-08-28"
end

@testset "last Thursday of September 2013" begin
    @test meetup(2013, 9, "last", "Thursday") == "2013-09-26"
end

@testset "last Thursday of October 2013" begin
    @test meetup(2013, 10, "last", "Thursday") == "2013-10-31"
end

@testset "last Friday of November 2013" begin
    @test meetup(2013, 11, "last", "Friday") == "2013-11-29"
end

@testset "last Friday of December 2013" begin
    @test meetup(2013, 12, "last", "Friday") == "2013-12-27"
end

@testset "last Saturday of January 2013" begin
    @test meetup(2013, 1, "last", "Saturday") == "2013-01-26"
end

@testset "last Saturday of February 2013" begin
    @test meetup(2013, 2, "last", "Saturday") == "2013-02-23"
end

@testset "last Sunday of March 2013" begin
    @test meetup(2013, 3, "last", "Sunday") == "2013-03-31"
end

@testset "last Sunday of April 2013" begin
    @test meetup(2013, 4, "last", "Sunday") == "2013-04-28"
end

@testset "last Wednesday of February 2012" begin
    @test meetup(2012, 2, "last", "Wednesday") == "2012-02-29"
end

@testset "last Wednesday of December 2014" begin
    @test meetup(2014, 12, "last", "Wednesday") == "2014-12-31"
end

@testset "last Sunday of February 2015" begin
    @test meetup(2015, 2, "last", "Sunday") == "2015-02-22"
end

@testset "first Friday of December 2012" begin
    @test meetup(2012, 12, "first", "Friday") == "2012-12-07"
end

