# canonical data version: 1.1.0
# This file was generated by a script.

using Test

include("poker.jl")

@testset "single hand always wins" begin
    @test best_hands(["4S 5S 7H 8D JC"]) == ["4S 5S 7H 8D JC"]
end

@testset "highest card out of all hands wins" begin
    @test best_hands(["4D 5S 6S 8D 3C", "2S 4C 7S 9H 10H", "3S 4S 5D 6H JH"]) == ["3S 4S 5D 6H JH"]
end

@testset "a tie has multiple winners" begin
    @test best_hands(["4D 5S 6S 8D 3C", "2S 4C 7S 9H 10H", "3S 4S 5D 6H JH", "3H 4H 5C 6C JD"]) == ["3S 4S 5D 6H JH", "3H 4H 5C 6C JD"]
end

@testset "multiple hands with the same high cards, tie compares next highest ranked, down to last card" begin
    @test best_hands(["3S 5H 6S 8D 7H", "2S 5D 6D 8C 7S"]) == ["3S 5H 6S 8D 7H"]
end

@testset "one pair beats high card" begin
    @test best_hands(["4S 5H 6C 8D KH", "2S 4H 6S 4D JH"]) == ["2S 4H 6S 4D JH"]
end

@testset "highest pair wins" begin
    @test best_hands(["4S 2H 6S 2D JH", "2S 4H 6C 4D JD"]) == ["2S 4H 6C 4D JD"]
end

@testset "two pairs beats one pair" begin
    @test best_hands(["2S 8H 6S 8D JH", "4S 5H 4C 8C 5C"]) == ["4S 5H 4C 8C 5C"]
end

@testset "both hands have two pairs, highest ranked pair wins" begin
    @test best_hands(["2S 8H 2D 8D 3H", "4S 5H 4C 8S 5D"]) == ["2S 8H 2D 8D 3H"]
end

@testset "both hands have two pairs, with the same highest ranked pair, tie goes to low pair" begin
    @test best_hands(["2S QS 2C QD JH", "JD QH JS 8D QC"]) == ["JD QH JS 8D QC"]
end

@testset "both hands have two identically ranked pairs, tie goes to remaining card (kicker)" begin
    @test best_hands(["JD QH JS 8D QC", "JS QS JC 2D QD"]) == ["JD QH JS 8D QC"]
end

@testset "three of a kind beats two pair" begin
    @test best_hands(["2S 8H 2H 8D JH", "4S 5H 4C 8S 4H"]) == ["4S 5H 4C 8S 4H"]
end

@testset "both hands have three of a kind, tie goes to highest ranked triplet" begin
    @test best_hands(["2S 2H 2C 8D JH", "4S AH AS 8C AD"]) == ["4S AH AS 8C AD"]
end

@testset "with multiple decks, two players can have same three of a kind, ties go to highest remaining cards" begin
    @test best_hands(["4S AH AS 7C AD", "4S AH AS 8C AD"]) == ["4S AH AS 8C AD"]
end

@testset "a straight beats three of a kind" begin
    @test best_hands(["4S 5H 4C 8D 4H", "3S 4D 2S 6D 5C"]) == ["3S 4D 2S 6D 5C"]
end

@testset "aces can end a straight (10 J Q K A)" begin
    @test best_hands(["4S 5H 4C 8D 4H", "10D JH QS KD AC"]) == ["10D JH QS KD AC"]
end

@testset "aces can start a straight (A 2 3 4 5)" begin
    @test best_hands(["4S 5H 4C 8D 4H", "4D AH 3S 2D 5C"]) == ["4D AH 3S 2D 5C"]
end

@testset "both hands with a straight, tie goes to highest ranked card" begin
    @test best_hands(["4S 6C 7S 8D 5H", "5S 7H 8S 9D 6H"]) == ["5S 7H 8S 9D 6H"]
end

@testset "even though an ace is usually high, a 5-high straight is the lowest-scoring straight" begin
    @test best_hands(["2H 3C 4D 5D 6H", "4S AH 3S 2D 5H"]) == ["2H 3C 4D 5D 6H"]
end

@testset "flush beats a straight" begin
    @test best_hands(["4C 6H 7D 8D 5H", "2S 4S 5S 6S 7S"]) == ["2S 4S 5S 6S 7S"]
end

@testset "both hands have a flush, tie goes to high card, down to the last one if necessary" begin
    @test best_hands(["4H 7H 8H 9H 6H", "2S 4S 5S 6S 7S"]) == ["4H 7H 8H 9H 6H"]
end

@testset "full house beats a flush" begin
    @test best_hands(["3H 6H 7H 8H 5H", "4S 5H 4C 5D 4H"]) == ["4S 5H 4C 5D 4H"]
end

@testset "both hands have a full house, tie goes to highest-ranked triplet" begin
    @test best_hands(["4H 4S 4D 9S 9D", "5H 5S 5D 8S 8D"]) == ["5H 5S 5D 8S 8D"]
end

@testset "with multiple decks, both hands have a full house with the same triplet, tie goes to the pair" begin
    @test best_hands(["5H 5S 5D 9S 9D", "5H 5S 5D 8S 8D"]) == ["5H 5S 5D 9S 9D"]
end

@testset "four of a kind beats a full house" begin
    @test best_hands(["4S 5H 4D 5D 4H", "3S 3H 2S 3D 3C"]) == ["3S 3H 2S 3D 3C"]
end

@testset "both hands have four of a kind, tie goes to high quad" begin
    @test best_hands(["2S 2H 2C 8D 2D", "4S 5H 5S 5D 5C"]) == ["4S 5H 5S 5D 5C"]
end

@testset "with multiple decks, both hands with identical four of a kind, tie determined by kicker" begin
    @test best_hands(["3S 3H 2S 3D 3C", "3S 3H 4S 3D 3C"]) == ["3S 3H 4S 3D 3C"]
end

@testset "straight flush beats four of a kind" begin
    @test best_hands(["4S 5H 5S 5D 5C", "7S 8S 9S 6S 10S"]) == ["7S 8S 9S 6S 10S"]
end

@testset "both hands have straight flush, tie goes to highest-ranked card" begin
    @test best_hands(["4H 6H 7H 8H 5H", "5S 7S 8S 9S 6S"]) == ["5S 7S 8S 9S 6S"]
end

