# canonical data version: 1.1.1
# This file was generated by a script.

using Test

include("protein-translation.jl")

@testset "Translate input RNA sequences into proteins" begin
    @testset "Methionine RNA sequence" begin
        @test proteins("AUG") == ["Methionine"]
    end
    @testset "Phenylalanine RNA sequence 1" begin
        @test proteins("UUU") == ["Phenylalanine"]
    end
    @testset "Phenylalanine RNA sequence 2" begin
        @test proteins("UUC") == ["Phenylalanine"]
    end
    @testset "Leucine RNA sequence 1" begin
        @test proteins("UUA") == ["Leucine"]
    end
    @testset "Leucine RNA sequence 2" begin
        @test proteins("UUG") == ["Leucine"]
    end
    @testset "Serine RNA sequence 1" begin
        @test proteins("UCU") == ["Serine"]
    end
    @testset "Serine RNA sequence 2" begin
        @test proteins("UCC") == ["Serine"]
    end
    @testset "Serine RNA sequence 3" begin
        @test proteins("UCA") == ["Serine"]
    end
    @testset "Serine RNA sequence 4" begin
        @test proteins("UCG") == ["Serine"]
    end
    @testset "Tyrosine RNA sequence 1" begin
        @test proteins("UAU") == ["Tyrosine"]
    end
    @testset "Tyrosine RNA sequence 2" begin
        @test proteins("UAC") == ["Tyrosine"]
    end
    @testset "Cysteine RNA sequence 1" begin
        @test proteins("UGU") == ["Cysteine"]
    end
    @testset "Cysteine RNA sequence 2" begin
        @test proteins("UGC") == ["Cysteine"]
    end
    @testset "Tryptophan RNA sequence" begin
        @test proteins("UGG") == ["Tryptophan"]
    end
    @testset "STOP codon RNA sequence 1" begin
        @test proteins("UAA") == []
    end
    @testset "STOP codon RNA sequence 2" begin
        @test proteins("UAG") == []
    end
    @testset "STOP codon RNA sequence 3" begin
        @test proteins("UGA") == []
    end
    @testset "Translate RNA strand into correct protein list" begin
        @test proteins("AUGUUUUGG") == ["Methionine", "Phenylalanine", "Tryptophan"]
    end
    @testset "Translation stops if STOP codon at beginning of sequence" begin
        @test proteins("UAGUGG") == []
    end
    @testset "Translation stops if STOP codon at end of two-codon sequence" begin
        @test proteins("UGGUAG") == ["Tryptophan"]
    end
    @testset "Translation stops if STOP codon at end of three-codon sequence" begin
        @test proteins("AUGUUUUAA") == ["Methionine", "Phenylalanine"]
    end
    @testset "Translation stops if STOP codon in middle of three-codon sequence" begin
        @test proteins("UGGUAGUGG") == ["Tryptophan"]
    end
    @testset "Translation stops if STOP codon in middle of six-codon sequence" begin
        @test proteins("UGGUGUUAUUAAUGGUUU") == ["Tryptophan", "Cysteine", "Tyrosine"]
    end
end

