# canonical data version: 1.1.0
# This file was generated by a script.

using Test

include("rectangles.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# The inputs are represented as arrays of strings to improve readability in this JSON file.
# Your track may choose whether to present the input as a single string (concatenating all the lines) or as the list.

@testset "no rows" begin
    @test rectangles([]) == 0
end

@testset "no columns" begin
    @test rectangles([""]) == 0
end

@testset "no rectangles" begin
    @test rectangles([" "]) == 0
end

@testset "one rectangle" begin
    @test rectangles(["+-+", "| |", "+-+"]) == 1
end

@testset "two rectangles without shared parts" begin
    @test rectangles(["  +-+", "  | |", "+-+-+", "| |  ", "+-+  "]) == 2
end

@testset "five rectangles with shared parts" begin
    @test rectangles(["  +-+", "  | |", "+-+-+", "| | |", "+-+-+"]) == 5
end

@testset "rectangle of height 1 is counted" begin
    @test rectangles(["+--+", "+--+"]) == 1
end

@testset "rectangle of width 1 is counted" begin
    @test rectangles(["++", "||", "++"]) == 1
end

@testset "1x1 square is counted" begin
    @test rectangles(["++", "++"]) == 1
end

@testset "only complete rectangles are counted" begin
    @test rectangles(["  +-+", "    |", "+-+-+", "| | -", "+-+-+"]) == 1
end

@testset "rectangles can be of different sizes" begin
    @test rectangles(["+------+----+", "|      |    |", "+---+--+    |", "|   |       |", "+---+-------+"]) == 3
end

@testset "corner is required for a rectangle to be complete" begin
    @test rectangles(["+------+----+", "|      |    |", "+------+    |", "|   |       |", "+---+-------+"]) == 2
end

@testset "large input with many rectangles" begin
    @test rectangles(["+---+--+----+", "|   +--+----+", "+---+--+    |", "|   +--+----+", "+---+--+--+-+", "+---+--+--+-+", "+------+  | |", "          +-+"]) == 60
end

