# canonical data version: 1.2.0
# This file was generated by a script.

using Test

include("reverse-string.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
# If property based testing tools are available, a good property to test is reversing a string twice: reverse(reverse(string)) == string

@testset "an empty string" begin
    @test reverse("") == ""
end

@testset "a word" begin
    @test reverse("robot") == "tobor"
end

@testset "a capitalized word" begin
    @test reverse("Ramen") == "nemaR"
end

@testset "a sentence with punctuation" begin
    @test reverse("I'm hungry!") == "!yrgnuh m'I"
end

@testset "a palindrome" begin
    @test reverse("racecar") == "racecar"
end

@testset "an even-sized word" begin
    @test reverse("drawer") == "reward"
end

