# canonical data version: 1.3.0
# This file was generated by a script.

using Test

include("rna-transcription.jl")

@testset "Empty RNA sequence" begin
    @test to_rna("") == ""
end

@testset "RNA complement of cytosine is guanine" begin
    @test to_rna("C") == "G"
end

@testset "RNA complement of guanine is cytosine" begin
    @test to_rna("G") == "C"
end

@testset "RNA complement of thymine is adenine" begin
    @test to_rna("T") == "A"
end

@testset "RNA complement of adenine is uracil" begin
    @test to_rna("A") == "U"
end

@testset "RNA complement" begin
    @test to_rna("ACGTGGTCTTAA") == "UGCACCAGAAUU"
end

