# canonical data version: 1.2.0
# This file was generated by a script.

using Test

include("roman-numerals.jl")

@testset "1 is a single I" begin
    @test roman(1) == "I"
end

@testset "2 is two I's" begin
    @test roman(2) == "II"
end

@testset "3 is three I's" begin
    @test roman(3) == "III"
end

@testset "4, being 5 - 1, is IV" begin
    @test roman(4) == "IV"
end

@testset "5 is a single V" begin
    @test roman(5) == "V"
end

@testset "6, being 5 + 1, is VI" begin
    @test roman(6) == "VI"
end

@testset "9, being 10 - 1, is IX" begin
    @test roman(9) == "IX"
end

@testset "20 is two X's" begin
    @test roman(27) == "XXVII"
end

@testset "48 is not 50 - 2 but rather 40 + 8" begin
    @test roman(48) == "XLVIII"
end

@testset "49 is not 40 + 5 + 4 but rather 50 - 10 + 10 - 1" begin
    @test roman(49) == "XLIX"
end

@testset "50 is a single L" begin
    @test roman(59) == "LIX"
end

@testset "90, being 100 - 10, is XC" begin
    @test roman(93) == "XCIII"
end

@testset "100 is a single C" begin
    @test roman(141) == "CXLI"
end

@testset "60, being 50 + 10, is LX" begin
    @test roman(163) == "CLXIII"
end

@testset "400, being 500 - 100, is CD" begin
    @test roman(402) == "CDII"
end

@testset "500 is a single D" begin
    @test roman(575) == "DLXXV"
end

@testset "900, being 1000 - 100, is CM" begin
    @test roman(911) == "CMXI"
end

@testset "1000 is a single M" begin
    @test roman(1024) == "MXXIV"
end

@testset "3000 is three M's" begin
    @test roman(3000) == "MMM"
end

