# canonical data version: 2.0.0
# This file was generated by a script.

using Test

include("satellite.jl")

@testset "Empty tree" begin
    @test tree_from_traversals([], []) == Dict()
end

@testset "Tree with one item" begin
    @test tree_from_traversals(["a"], ["a"]) == Dict("v" => "a", "l" => Dict(), "r" => Dict())
end

@testset "Tree with many items" begin
    @test tree_from_traversals(["a", "i", "x", "f", "r"], ["i", "a", "f", "x", "r"]) == Dict("v" => "a", "l" => Dict("v" => "i", "l" => Dict(), "r" => Dict()), "r" => Dict("v" => "x", "l" => Dict("v" => "f", "l" => Dict(), "r" => Dict()), "r" => Dict("v" => "r", "l" => Dict(), "r" => Dict())))
end

@testset "Reject traversals of different length" begin
    @test_throws ArgumentError tree_from_traversals(["a", "b"], ["b", "a", "r"])
end

@testset "Reject inconsistent traversals of same length" begin
    @test_throws ArgumentError tree_from_traversals(["x", "y", "z"], ["a", "b", "c"])
end

@testset "Reject traversals with repeated items" begin
    @test_throws ArgumentError tree_from_traversals(["a", "b", "a"], ["b", "a", "a"])
end

