# canonical data version: 1.2.0
# This file was generated by a script.

using Test

include("secret-handshake.jl")

# The following lines are top-level comments in canonical-data.json; comments within cases
# are not included. Do not include these comments in the exercise's runtests.jl.
#
#  In a discussion in https://github.com/exercism/problem-specifications/pull/794 and    
#  https://github.com/exercism/problem-specifications/issues/335 it has been decided to  
#  only include numbers between 0 and 31 (00000 to 11111) in the canonical 
#  test data.                                                              
#                                                                          
#  This is to allow for different implementations in different tracks and  
#  not restrict solutions to bitwise or modulo-based algorithms.           
#                                                                          
#  Tracks may include additional tests for numbers > 31 in their test      
#  suites. In this case, 32 (100000) should yield the same result as 0,    
#  33 (100001) should yield the same result as 1, and so on.               

@testset "Create a handshake for a number" begin
    @testset "wink for 1" begin
        @test commands(1) == ["wink"]
    end
    @testset "double blink for 10" begin
        @test commands(2) == ["double blink"]
    end
    @testset "close your eyes for 100" begin
        @test commands(4) == ["close your eyes"]
    end
    @testset "jump for 1000" begin
        @test commands(8) == ["jump"]
    end
    @testset "combine two actions" begin
        @test commands(3) == ["wink", "double blink"]
    end
    @testset "reverse two actions" begin
        @test commands(19) == ["double blink", "wink"]
    end
    @testset "reversing one action gives the same action" begin
        @test commands(24) == ["jump"]
    end
    @testset "reversing no actions still gives no actions" begin
        @test commands(16) == []
    end
    @testset "all possible actions" begin
        @test commands(15) == ["wink", "double blink", "close your eyes", "jump"]
    end
    @testset "reverse all possible actions" begin
        @test commands(31) == ["jump", "close your eyes", "double blink", "wink"]
    end
    @testset "do nothing for zero" begin
        @test commands(0) == []
    end
end

