# canonical data version: 1.2.0
# This file was generated by a script.

using Test

include("space-age.jl")

@testset "age on Earth" begin
    @test age("Earth", 1000000000) == 31.69
end

@testset "age on Mercury" begin
    @test age("Mercury", 2134835688) == 280.88
end

@testset "age on Venus" begin
    @test age("Venus", 189839836) == 9.78
end

@testset "age on Mars" begin
    @test age("Mars", 2129871239) == 35.88
end

@testset "age on Jupiter" begin
    @test age("Jupiter", 901876382) == 2.41
end

@testset "age on Saturn" begin
    @test age("Saturn", 2000000000) == 2.15
end

@testset "age on Uranus" begin
    @test age("Uranus", 1210123456) == 0.46
end

@testset "age on Neptune" begin
    @test age("Neptune", 1821023456) == 0.35
end

