# canonical data version: 1.1.0
# This file was generated by a script.

using Test

include("spiral-matrix.jl")

@testset "empty spiral" begin
    @test spiral_matrix(0) == []
end

@testset "trivial spiral" begin
    @test spiral_matrix(1) == [[1]]
end

@testset "spiral of size 2" begin
    @test spiral_matrix(2) == [[1, 2], [4, 3]]
end

@testset "spiral of size 3" begin
    @test spiral_matrix(3) == [[1, 2, 3], [8, 9, 4], [7, 6, 5]]
end

@testset "spiral of size 4" begin
    @test spiral_matrix(4) == [[1, 2, 3, 4], [12, 13, 14, 5], [11, 16, 15, 6], [10, 9, 8, 7]]
end

@testset "spiral of size 5" begin
    @test spiral_matrix(5) == [[1, 2, 3, 4, 5], [16, 17, 18, 19, 6], [15, 24, 25, 20, 7], [14, 23, 22, 21, 8], [13, 12, 11, 10, 9]]
end

