# canonical data version: 1.4.0
# This file was generated by a script.

using Test

include("two-bucket.jl")

@testset "Measure using bucket one of size 3 and bucket two of size 5 - start with bucket one" begin
    @test measure(3, 5, 1, "one") == Dict("moves" => 4, "goalBucket" => "one", "otherBucket" => 5)
end

@testset "Measure using bucket one of size 3 and bucket two of size 5 - start with bucket two" begin
    @test measure(3, 5, 1, "two") == Dict("moves" => 8, "goalBucket" => "two", "otherBucket" => 3)
end

@testset "Measure using bucket one of size 7 and bucket two of size 11 - start with bucket one" begin
    @test measure(7, 11, 2, "one") == Dict("moves" => 14, "goalBucket" => "one", "otherBucket" => 11)
end

@testset "Measure using bucket one of size 7 and bucket two of size 11 - start with bucket two" begin
    @test measure(7, 11, 2, "two") == Dict("moves" => 18, "goalBucket" => "two", "otherBucket" => 7)
end

@testset "Measure one step using bucket one of size 1 and bucket two of size 3 - start with bucket two" begin
    @test measure(1, 3, 3, "two") == Dict("moves" => 1, "goalBucket" => "two", "otherBucket" => 0)
end

@testset "Measure using bucket one of size 2 and bucket two of size 3 - start with bucket one and end with bucket two" begin
    @test measure(2, 3, 3, "one") == Dict("moves" => 2, "goalBucket" => "two", "otherBucket" => 2)
end

