# canonical data version: 1.2.0
# This file was generated by a script.

using Test

include("two-fer.jl")

@testset "no name given" begin
    @test two_fer(nothing) == "One for you, one for me."
end

@testset "a name given" begin
    @test two_fer("Alice") == "One for Alice, one for me."
end

@testset "another name given" begin
    @test two_fer("Bob") == "One for Bob, one for me."
end

