# canonical data version: 1.1.0
# This file was generated by a script.

using Test

include("zebra-puzzle.jl")

@testset "resident who drinks water" begin
    @test drinks_water() == "Norwegian"
end

@testset "resident who owns zebra" begin
    @test owns_zebra() == "Japanese"
end

