name: 'Check exercise files exist'

on: [push, pull_request]

jobs:
  check-files-exist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check exercise files exist
      run: ./bin/check-files-exist.sh
