name: 'Generate Jupyter notebooks'

on:
  issue_comment:
    types: [created]

jobs:
  format:
    name: 'Generate Jupyter notebooks'
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/make-notebooks')
    steps:
      - name: 'Checkout code'
        run: |
          PR_DATA="/tmp/pr.json"

          jq -r ".issue.pull_request.url" "$GITHUB_EVENT_PATH" | \
            xargs curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -o "$PR_DATA" --url

          HEAD_REF=$(jq -r ".head.ref" "$PR_DATA")
          HEAD_REPO=$(jq -r '.head.repo.clone_url | sub("https://"; "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@")' "$PR_DATA")

          git clone $HEAD_REPO .
          git checkout -b "$HEAD_REF" "origin/$HEAD_REF"

      - name: 'Generate notebooks'
        run: julia bin/generate-notebooks.jl

      - name: 'Commit generated notebooks'
        run: |
          # Check if there is nothing to commit (i.e. no formatting changes made)
          if [ -z "$(git status --porcelain)" ]; then
            echo "Notebooks have already been generated."
            exit 0
          fi

          # Setup the git user (required to commit anything)
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Commit the changes
          git add .
          git commit -m "Generate notebooks"
          git push
