name: Tools

on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml
      - .github/workflows/sync-labels.yml
  schedule:
    - cron: 6 6 6 * *
  workflow_dispatch:

jobs:
  sync-labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # 1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
